/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.AuthTokenCreateApiOperation;
import org.openapis.openapi.utils.Utils;

public class AuthTokenCreateApiRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final AuthTokenCreateApiRequest.Builder pojoBuilder;
    private AuthTokenCreateApiRequest request;
    private boolean _setterCalled;

    public AuthTokenCreateApiRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = AuthTokenCreateApiRequest.builder();
    }

    public AuthTokenCreateApiRequestBuilder serviceId(@Nonnull String serviceId) {
        this.pojoBuilder.serviceId(serviceId);
        this._setterCalled = true;
        return this;
    }

    public AuthTokenCreateApiRequestBuilder requestBody(@Nonnull AuthTokenCreateApiRequestBody requestBody) {
        this.pojoBuilder.requestBody(requestBody);
        this._setterCalled = true;
        return this;
    }

    private AuthTokenCreateApiRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public AuthTokenCreateApiResponse call() throws Exception {
        RequestOperation<AuthTokenCreateApiRequest, AuthTokenCreateApiResponse> operation
              = new AuthTokenCreateApiOperation(sdkConfiguration);

        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
