/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

/**
 * AuthTokenUpdateApiFormAuthorizationDetails
 * 
 * <p>The authorization details. This represents the value of the `authorization_details`
 * request parameter in the preceding device authorization request which is defined in
 * "OAuth 2.0 Rich Authorization Requests".
 */
public class AuthTokenUpdateApiFormAuthorizationDetails {
    /**
     * Elements of this authorization details.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("elements")
    private List<AuthTokenUpdateApiFormElement> elements;

    @JsonCreator
    public AuthTokenUpdateApiFormAuthorizationDetails(
            @JsonProperty("elements") @Nullable List<AuthTokenUpdateApiFormElement> elements) {
        this.elements = elements;
    }
    
    public AuthTokenUpdateApiFormAuthorizationDetails() {
        this(null);
    }

    /**
     * Elements of this authorization details.
     */
    public Optional<List<AuthTokenUpdateApiFormElement>> elements() {
        return Optional.ofNullable(this.elements);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Elements of this authorization details.
     */
    public AuthTokenUpdateApiFormAuthorizationDetails withElements(@Nullable List<AuthTokenUpdateApiFormElement> elements) {
        this.elements = elements;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuthTokenUpdateApiFormAuthorizationDetails other = (AuthTokenUpdateApiFormAuthorizationDetails) o;
        return 
            Utils.enhancedDeepEquals(this.elements, other.elements);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            elements);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AuthTokenUpdateApiFormAuthorizationDetails.class,
                "elements", elements);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<AuthTokenUpdateApiFormElement> elements;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Elements of this authorization details.
         */
        public Builder elements(@Nullable List<AuthTokenUpdateApiFormElement> elements) {
            this.elements = elements;
            return this;
        }

        public AuthTokenUpdateApiFormAuthorizationDetails build() {
            return new AuthTokenUpdateApiFormAuthorizationDetails(
                elements);
        }

    }
}
