/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.AuthIntrospectionStandardApiOperation;
import org.openapis.openapi.utils.Utils;

public class AuthIntrospectionStandardApiRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final AuthIntrospectionStandardApiRequest.Builder pojoBuilder;
    private AuthIntrospectionStandardApiRequest request;
    private boolean _setterCalled;

    public AuthIntrospectionStandardApiRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = AuthIntrospectionStandardApiRequest.builder();
    }

    public AuthIntrospectionStandardApiRequestBuilder serviceId(@Nonnull String serviceId) {
        this.pojoBuilder.serviceId(serviceId);
        this._setterCalled = true;
        return this;
    }

    public AuthIntrospectionStandardApiRequestBuilder requestBody(@Nonnull AuthIntrospectionStandardApiRequestBody requestBody) {
        this.pojoBuilder.requestBody(requestBody);
        this._setterCalled = true;
        return this;
    }

    private AuthIntrospectionStandardApiRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public AuthIntrospectionStandardApiResponse call() throws Exception {
        RequestOperation<AuthIntrospectionStandardApiRequest, AuthIntrospectionStandardApiResponse> operation
              = new AuthIntrospectionStandardApiOperation(sdkConfiguration);

        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
