/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.AuthRevocationApi;
import org.openapis.openapi.utils.Utils;

public class AuthRevocationApiRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final AuthRevocationApiRequest.Builder pojoBuilder;
    private AuthRevocationApiRequest request;
    private String serverURL;
    private boolean _setterCalled;

    public AuthRevocationApiRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = AuthRevocationApiRequest.builder();
    }

    public AuthRevocationApiRequestBuilder serviceId(@Nonnull String serviceId) {
        this.pojoBuilder.serviceId(serviceId);
        this._setterCalled = true;
        return this;
    }

    public AuthRevocationApiRequestBuilder requestBody(@Nonnull AuthRevocationApiRequestBody requestBody) {
        this.pojoBuilder.requestBody(requestBody);
        this._setterCalled = true;
        return this;
    }

    public AuthRevocationApiRequestBuilder serverURL(@Nullable String serverURL) {
        this.serverURL = serverURL;
        return this;
    }

    private AuthRevocationApiRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public AuthRevocationApiResponse call() throws Exception {
        RequestOperation<AuthRevocationApiRequest, AuthRevocationApiResponse> operation
              = new AuthRevocationApi.Sync(sdkConfiguration, serverURL);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
