/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.AuthIntrospectionApiOperation;
import org.openapis.openapi.utils.Utils;

public class AuthIntrospectionApiRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final AuthIntrospectionApiRequest.Builder pojoBuilder;
    private AuthIntrospectionApiRequest request;
    private String serverURL;
    private boolean _setterCalled;

    public AuthIntrospectionApiRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = AuthIntrospectionApiRequest.builder();
    }

    public AuthIntrospectionApiRequestBuilder serviceId(@Nonnull String serviceId) {
        this.pojoBuilder.serviceId(serviceId);
        this._setterCalled = true;
        return this;
    }

    public AuthIntrospectionApiRequestBuilder requestBody(@Nonnull AuthIntrospectionApiRequestBody requestBody) {
        this.pojoBuilder.requestBody(requestBody);
        this._setterCalled = true;
        return this;
    }

    public AuthIntrospectionApiRequestBuilder serverURL(@Nullable String serverURL) {
        this.serverURL = serverURL;
        return this;
    }

    private AuthIntrospectionApiRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public AuthIntrospectionApiResponse call() throws Exception {
        RequestOperation<AuthIntrospectionApiRequest, AuthIntrospectionApiResponse> operation
              = new AuthIntrospectionApiOperation(sdkConfiguration, serverURL);

        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
