/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * AuthTokenFailApiFormAction
 * 
 * <p>The next action that the authorization server implementation should take.
 */
public enum AuthTokenFailApiFormAction {
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    BAD_REQUEST("BAD_REQUEST");

    @JsonValue
    private final String value;

    AuthTokenFailApiFormAction(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<AuthTokenFailApiFormAction> fromValue(String value) {
        for (AuthTokenFailApiFormAction o: AuthTokenFailApiFormAction.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

