/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * AuthUserinfoIssueApiFormAction
 * 
 * <p>The next action that the authorization server implementation should take.
 */
public enum AuthUserinfoIssueApiFormAction {
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    BAD_REQUEST("BAD_REQUEST"),
    UNAUTHORIZED("UNAUTHORIZED"),
    FORBIDDEN("FORBIDDEN"),
    JSON("JSON"),
    OK("OK");

    @JsonValue
    private final String value;

    AuthUserinfoIssueApiFormAction(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<AuthUserinfoIssueApiFormAction> fromValue(String value) {
        for (AuthUserinfoIssueApiFormAction o: AuthUserinfoIssueApiFormAction.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

