/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * AuthAuthorizationIssueApiFormAction
 * 
 * <p>The next action that the authorization server implementation should take.
 */
public enum AuthAuthorizationIssueApiFormAction {
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    BAD_REQUEST("BAD_REQUEST"),
    LOCATION("LOCATION"),
    FORM("FORM");

    @JsonValue
    private final String value;

    AuthAuthorizationIssueApiFormAction(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<AuthAuthorizationIssueApiFormAction> fromValue(String value) {
        for (AuthAuthorizationIssueApiFormAction o: AuthAuthorizationIssueApiFormAction.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

