/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.AuthTokenIssueApiOperation;
import org.openapis.openapi.utils.Utils;

public class AuthTokenIssueApiRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final AuthTokenIssueApiRequest.Builder pojoBuilder;
    private AuthTokenIssueApiRequest request;
    private String serverURL;
    private boolean _setterCalled;

    public AuthTokenIssueApiRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = AuthTokenIssueApiRequest.builder();
    }

    public AuthTokenIssueApiRequestBuilder serviceId(@Nonnull String serviceId) {
        this.pojoBuilder.serviceId(serviceId);
        this._setterCalled = true;
        return this;
    }

    public AuthTokenIssueApiRequestBuilder requestBody(@Nonnull AuthTokenIssueApiRequestBody requestBody) {
        this.pojoBuilder.requestBody(requestBody);
        this._setterCalled = true;
        return this;
    }

    public AuthTokenIssueApiRequestBuilder serverURL(@Nullable String serverURL) {
        this.serverURL = serverURL;
        return this;
    }

    private AuthTokenIssueApiRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public AuthTokenIssueApiResponse call() throws Exception {
        RequestOperation<AuthTokenIssueApiRequest, AuthTokenIssueApiResponse> operation
              = new AuthTokenIssueApiOperation(sdkConfiguration, serverURL);

        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
