/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import org.openapis.openapi.models.components.Property;
import org.openapis.openapi.utils.Utils;


public class AuthTokenIssueApiRequestBody {
    /**
     * The ticket issued from Authlete `/auth/token` API.
     */
    @JsonProperty("ticket")
    private String ticket;

    /**
     * The subject (= unique identifier) of the authenticated user.
     */
    @JsonProperty("subject")
    private String subject;

    /**
     * Extra properties to associate with a newly created access token. Note that properties parameter is accepted only
     * when `Content-Type` of the request is `application/json`, so don't use `application/x-www-form-urlencoded`
     * if you want to specify properties.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("properties")
    private List<Property> properties;

    /**
     * Additional claims that are added to the payload part of the JWT access token.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("jwtAtClaims")
    private String jwtAtClaims;

    /**
     * The representation of an access token that may be issued as a result of the Authlete API call.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("accessToken")
    private String accessToken;

    @JsonCreator
    public AuthTokenIssueApiRequestBody(
            @JsonProperty("ticket") @Nonnull String ticket,
            @JsonProperty("subject") @Nonnull String subject,
            @JsonProperty("properties") @Nullable List<Property> properties,
            @JsonProperty("jwtAtClaims") @Nullable String jwtAtClaims,
            @JsonProperty("accessToken") @Nullable String accessToken) {
        this.ticket = Optional.ofNullable(ticket)
            .orElseThrow(() -> new IllegalArgumentException("ticket cannot be null"));
        this.subject = Optional.ofNullable(subject)
            .orElseThrow(() -> new IllegalArgumentException("subject cannot be null"));
        this.properties = properties;
        this.jwtAtClaims = jwtAtClaims;
        this.accessToken = accessToken;
    }
    
    public AuthTokenIssueApiRequestBody(
            @Nonnull String ticket,
            @Nonnull String subject) {
        this(ticket, subject, null,
            null, null);
    }

    /**
     * The ticket issued from Authlete `/auth/token` API.
     */
    public String ticket() {
        return this.ticket;
    }

    /**
     * The subject (= unique identifier) of the authenticated user.
     */
    public String subject() {
        return this.subject;
    }

    /**
     * Extra properties to associate with a newly created access token. Note that properties parameter is accepted only
     * when `Content-Type` of the request is `application/json`, so don't use `application/x-www-form-urlencoded`
     * if you want to specify properties.
     */
    public Optional<List<Property>> properties() {
        return Optional.ofNullable(this.properties);
    }

    /**
     * Additional claims that are added to the payload part of the JWT access token.
     */
    public Optional<String> jwtAtClaims() {
        return Optional.ofNullable(this.jwtAtClaims);
    }

    /**
     * The representation of an access token that may be issued as a result of the Authlete API call.
     */
    public Optional<String> accessToken() {
        return Optional.ofNullable(this.accessToken);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The ticket issued from Authlete `/auth/token` API.
     */
    public AuthTokenIssueApiRequestBody withTicket(@Nonnull String ticket) {
        this.ticket = Utils.checkNotNull(ticket, "ticket");
        return this;
    }


    /**
     * The subject (= unique identifier) of the authenticated user.
     */
    public AuthTokenIssueApiRequestBody withSubject(@Nonnull String subject) {
        this.subject = Utils.checkNotNull(subject, "subject");
        return this;
    }


    /**
     * Extra properties to associate with a newly created access token. Note that properties parameter is accepted only
     * when `Content-Type` of the request is `application/json`, so don't use `application/x-www-form-urlencoded`
     * if you want to specify properties.
     */
    public AuthTokenIssueApiRequestBody withProperties(@Nullable List<Property> properties) {
        this.properties = properties;
        return this;
    }


    /**
     * Additional claims that are added to the payload part of the JWT access token.
     */
    public AuthTokenIssueApiRequestBody withJwtAtClaims(@Nullable String jwtAtClaims) {
        this.jwtAtClaims = jwtAtClaims;
        return this;
    }


    /**
     * The representation of an access token that may be issued as a result of the Authlete API call.
     */
    public AuthTokenIssueApiRequestBody withAccessToken(@Nullable String accessToken) {
        this.accessToken = accessToken;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuthTokenIssueApiRequestBody other = (AuthTokenIssueApiRequestBody) o;
        return 
            Utils.enhancedDeepEquals(this.ticket, other.ticket) &&
            Utils.enhancedDeepEquals(this.subject, other.subject) &&
            Utils.enhancedDeepEquals(this.properties, other.properties) &&
            Utils.enhancedDeepEquals(this.jwtAtClaims, other.jwtAtClaims) &&
            Utils.enhancedDeepEquals(this.accessToken, other.accessToken);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            ticket, subject, properties,
            jwtAtClaims, accessToken);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AuthTokenIssueApiRequestBody.class,
                "ticket", ticket,
                "subject", subject,
                "properties", properties,
                "jwtAtClaims", jwtAtClaims,
                "accessToken", accessToken);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String ticket;

        private String subject;

        private List<Property> properties;

        private String jwtAtClaims;

        private String accessToken;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The ticket issued from Authlete `/auth/token` API.
         */
        public Builder ticket(@Nonnull String ticket) {
            this.ticket = Utils.checkNotNull(ticket, "ticket");
            return this;
        }

        /**
         * The subject (= unique identifier) of the authenticated user.
         */
        public Builder subject(@Nonnull String subject) {
            this.subject = Utils.checkNotNull(subject, "subject");
            return this;
        }

        /**
         * Extra properties to associate with a newly created access token. Note that properties parameter is accepted only
         * when `Content-Type` of the request is `application/json`, so don't use `application/x-www-form-urlencoded`
         * if you want to specify properties.
         */
        public Builder properties(@Nullable List<Property> properties) {
            this.properties = properties;
            return this;
        }

        /**
         * Additional claims that are added to the payload part of the JWT access token.
         */
        public Builder jwtAtClaims(@Nullable String jwtAtClaims) {
            this.jwtAtClaims = jwtAtClaims;
            return this;
        }

        /**
         * The representation of an access token that may be issued as a result of the Authlete API call.
         */
        public Builder accessToken(@Nullable String accessToken) {
            this.accessToken = accessToken;
            return this;
        }

        public AuthTokenIssueApiRequestBody build() {
            return new AuthTokenIssueApiRequestBody(
                ticket, subject, properties,
                jwtAtClaims, accessToken);
        }

    }
}
