/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * AuthRevocationApiAction
 * 
 * <p>The next action that the authorization server implementation should take.
 */
public enum AuthRevocationApiAction {
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    INVALID_CLIENT("INVALID_CLIENT"),
    BAD_REQUEST("BAD_REQUEST"),
    OK("OK");

    @JsonValue
    private final String value;

    AuthRevocationApiAction(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<AuthRevocationApiAction> fromValue(String value) {
        for (AuthRevocationApiAction o: AuthRevocationApiAction.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

