/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.ClientRegistrationDeleteApi;
import org.openapis.openapi.utils.Utils;

public class ClientRegistrationDeleteApiRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final ClientRegistrationDeleteApiRequest.Builder pojoBuilder;
    private ClientRegistrationDeleteApiRequest request;
    private String serverURL;
    private boolean _setterCalled;

    public ClientRegistrationDeleteApiRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = ClientRegistrationDeleteApiRequest.builder();
    }

    public ClientRegistrationDeleteApiRequestBuilder serviceId(@Nonnull String serviceId) {
        this.pojoBuilder.serviceId(serviceId);
        this._setterCalled = true;
        return this;
    }

    public ClientRegistrationDeleteApiRequestBuilder requestBody(@Nonnull ClientRegistrationDeleteApiRequestBody requestBody) {
        this.pojoBuilder.requestBody(requestBody);
        this._setterCalled = true;
        return this;
    }

    public ClientRegistrationDeleteApiRequestBuilder serverURL(@Nullable String serverURL) {
        this.serverURL = serverURL;
        return this;
    }

    private ClientRegistrationDeleteApiRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public ClientRegistrationDeleteApiResponse call() throws Exception {
        RequestOperation<ClientRegistrationDeleteApiRequest, ClientRegistrationDeleteApiResponse> operation
              = new ClientRegistrationDeleteApi.Sync(sdkConfiguration, serverURL);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
