/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * ClientUpdateApiApplicationTypeRequest
 * 
 * <p>The application type. The value of this property affects the validation steps for a redirect URI.
 * See the description about `redirectUris` property for more details.
 */
public enum ClientUpdateApiApplicationTypeRequest {
    WEB("WEB"),
    NATIVE("NATIVE");

    @JsonValue
    private final String value;

    ClientUpdateApiApplicationTypeRequest(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ClientUpdateApiApplicationTypeRequest> fromValue(String value) {
        for (ClientUpdateApiApplicationTypeRequest o: ClientUpdateApiApplicationTypeRequest.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

