/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;


public class ClientExtensionRequestablesScopesGetApiResponseBody {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("requestableScopes")
    private List<String> requestableScopes;

    @JsonCreator
    public ClientExtensionRequestablesScopesGetApiResponseBody(
            @JsonProperty("requestableScopes") @Nullable List<String> requestableScopes) {
        this.requestableScopes = requestableScopes;
    }
    
    public ClientExtensionRequestablesScopesGetApiResponseBody() {
        this(null);
    }

    public Optional<List<String>> requestableScopes() {
        return Optional.ofNullable(this.requestableScopes);
    }

    public static Builder builder() {
        return new Builder();
    }


    public ClientExtensionRequestablesScopesGetApiResponseBody withRequestableScopes(@Nullable List<String> requestableScopes) {
        this.requestableScopes = requestableScopes;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ClientExtensionRequestablesScopesGetApiResponseBody other = (ClientExtensionRequestablesScopesGetApiResponseBody) o;
        return 
            Utils.enhancedDeepEquals(this.requestableScopes, other.requestableScopes);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            requestableScopes);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ClientExtensionRequestablesScopesGetApiResponseBody.class,
                "requestableScopes", requestableScopes);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private List<String> requestableScopes;

        private Builder() {
          // force use of static builder() method
        }

        public Builder requestableScopes(@Nullable List<String> requestableScopes) {
            this.requestableScopes = requestableScopes;
            return this;
        }

        public ClientExtensionRequestablesScopesGetApiResponseBody build() {
            return new ClientExtensionRequestablesScopesGetApiResponseBody(
                requestableScopes);
        }

    }
}
