/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.models.components.1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class ClientSecretUpdateApiFormRequest {
    /**
     * A service ID.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=serviceId")
    private String serviceId;

    /**
     * The client ID or the client ID alias of a client.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=clientIdentifier")
    private String clientIdentifier;


    @SpeakeasyMetadata("request:mediaType=application/x-www-form-urlencoded")
    private 1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema 1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema;

    @JsonCreator
    public ClientSecretUpdateApiFormRequest(
            @Nonnull String serviceId,
            @Nonnull String clientIdentifier,
            @Nonnull 1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema 1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema) {
        this.serviceId = Optional.ofNullable(serviceId)
            .orElseThrow(() -> new IllegalArgumentException("serviceId cannot be null"));
        this.clientIdentifier = Optional.ofNullable(clientIdentifier)
            .orElseThrow(() -> new IllegalArgumentException("clientIdentifier cannot be null"));
        this.1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema = Optional.ofNullable(1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema)
            .orElseThrow(() -> new IllegalArgumentException("1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema cannot be null"));
    }

    /**
     * A service ID.
     */
    public String serviceId() {
        return this.serviceId;
    }

    /**
     * The client ID or the client ID alias of a client.
     */
    public String clientIdentifier() {
        return this.clientIdentifier;
    }

    public 1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema 1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema() {
        return this.1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * A service ID.
     */
    public ClientSecretUpdateApiFormRequest withServiceId(@Nonnull String serviceId) {
        this.serviceId = Utils.checkNotNull(serviceId, "serviceId");
        return this;
    }


    /**
     * The client ID or the client ID alias of a client.
     */
    public ClientSecretUpdateApiFormRequest withClientIdentifier(@Nonnull String clientIdentifier) {
        this.clientIdentifier = Utils.checkNotNull(clientIdentifier, "clientIdentifier");
        return this;
    }


    public ClientSecretUpdateApiFormRequest with1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema(@Nonnull 1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema 1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema) {
        this.1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema = Utils.checkNotNull(1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema, "1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ClientSecretUpdateApiFormRequest other = (ClientSecretUpdateApiFormRequest) o;
        return 
            Utils.enhancedDeepEquals(this.serviceId, other.serviceId) &&
            Utils.enhancedDeepEquals(this.clientIdentifier, other.clientIdentifier) &&
            Utils.enhancedDeepEquals(this.1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema, other.1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            serviceId, clientIdentifier, 1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ClientSecretUpdateApiFormRequest.class,
                "serviceId", serviceId,
                "clientIdentifier", clientIdentifier,
                "1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema", 1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String serviceId;

        private String clientIdentifier;

        private 1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema 1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * A service ID.
         */
        public Builder serviceId(@Nonnull String serviceId) {
            this.serviceId = Utils.checkNotNull(serviceId, "serviceId");
            return this;
        }

        /**
         * The client ID or the client ID alias of a client.
         */
        public Builder clientIdentifier(@Nonnull String clientIdentifier) {
            this.clientIdentifier = Utils.checkNotNull(clientIdentifier, "clientIdentifier");
            return this;
        }

        public Builder 1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema(@Nonnull 1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema 1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema) {
            this.1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema = Utils.checkNotNull(1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema, "1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema");
            return this;
        }

        public ClientSecretUpdateApiFormRequest build() {
            return new ClientSecretUpdateApiFormRequest(
                serviceId, clientIdentifier, 1api1Percent7BserviceIdPercent7D1client1secret1update1Percent7BclientIdentifierPercent7DPostRequestBodyContentApplication1jsonSchema);
        }

    }
}
