/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;


public class ClientGetListApiResponseBody {
    /**
     * Start index (inclusive) of the result set of the query.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("start")
    private Integer start;

    /**
     * End index (exclusive) of the result set of the query.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("end")
    private Integer end;

    /**
     * Total number of clients that belong to the service. This doesn't mean the number of clients
     * contained in the response.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("totalCount")
    private Integer totalCount;

    /**
     * An array of clients.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("clients")
    private List<ClientGetListApiClient> clients;

    @JsonCreator
    public ClientGetListApiResponseBody(
            @JsonProperty("start") @Nullable Integer start,
            @JsonProperty("end") @Nullable Integer end,
            @JsonProperty("totalCount") @Nullable Integer totalCount,
            @JsonProperty("clients") @Nullable List<ClientGetListApiClient> clients) {
        this.start = start;
        this.end = end;
        this.totalCount = totalCount;
        this.clients = clients;
    }
    
    public ClientGetListApiResponseBody() {
        this(null, null, null,
            null);
    }

    /**
     * Start index (inclusive) of the result set of the query.
     */
    public Optional<Integer> start() {
        return Optional.ofNullable(this.start);
    }

    /**
     * End index (exclusive) of the result set of the query.
     */
    public Optional<Integer> end() {
        return Optional.ofNullable(this.end);
    }

    /**
     * Total number of clients that belong to the service. This doesn't mean the number of clients
     * contained in the response.
     */
    public Optional<Integer> totalCount() {
        return Optional.ofNullable(this.totalCount);
    }

    /**
     * An array of clients.
     */
    public Optional<List<ClientGetListApiClient>> clients() {
        return Optional.ofNullable(this.clients);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Start index (inclusive) of the result set of the query.
     */
    public ClientGetListApiResponseBody withStart(@Nullable Integer start) {
        this.start = start;
        return this;
    }


    /**
     * End index (exclusive) of the result set of the query.
     */
    public ClientGetListApiResponseBody withEnd(@Nullable Integer end) {
        this.end = end;
        return this;
    }


    /**
     * Total number of clients that belong to the service. This doesn't mean the number of clients
     * contained in the response.
     */
    public ClientGetListApiResponseBody withTotalCount(@Nullable Integer totalCount) {
        this.totalCount = totalCount;
        return this;
    }


    /**
     * An array of clients.
     */
    public ClientGetListApiResponseBody withClients(@Nullable List<ClientGetListApiClient> clients) {
        this.clients = clients;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ClientGetListApiResponseBody other = (ClientGetListApiResponseBody) o;
        return 
            Utils.enhancedDeepEquals(this.start, other.start) &&
            Utils.enhancedDeepEquals(this.end, other.end) &&
            Utils.enhancedDeepEquals(this.totalCount, other.totalCount) &&
            Utils.enhancedDeepEquals(this.clients, other.clients);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            start, end, totalCount,
            clients);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ClientGetListApiResponseBody.class,
                "start", start,
                "end", end,
                "totalCount", totalCount,
                "clients", clients);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Integer start;

        private Integer end;

        private Integer totalCount;

        private List<ClientGetListApiClient> clients;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Start index (inclusive) of the result set of the query.
         */
        public Builder start(@Nullable Integer start) {
            this.start = start;
            return this;
        }

        /**
         * End index (exclusive) of the result set of the query.
         */
        public Builder end(@Nullable Integer end) {
            this.end = end;
            return this;
        }

        /**
         * Total number of clients that belong to the service. This doesn't mean the number of clients
         * contained in the response.
         */
        public Builder totalCount(@Nullable Integer totalCount) {
            this.totalCount = totalCount;
            return this;
        }

        /**
         * An array of clients.
         */
        public Builder clients(@Nullable List<ClientGetListApiClient> clients) {
            this.clients = clients;
            return this;
        }

        public ClientGetListApiResponseBody build() {
            return new ClientGetListApiResponseBody(
                start, end, totalCount,
                clients);
        }

    }
}
