/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.1api1Percent7BserviceIdPercent7D1client1authorization1update1Percent7BclientIdPercent7DPostRequestBodyContentApplication1jsonSchema;
import org.openapis.openapi.operations.ClientAuthorizationUpdateApiFormOperation;
import org.openapis.openapi.utils.Utils;

public class ClientAuthorizationUpdateApiFormRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final ClientAuthorizationUpdateApiFormRequest.Builder pojoBuilder;
    private ClientAuthorizationUpdateApiFormRequest request;
    private boolean _setterCalled;

    public ClientAuthorizationUpdateApiFormRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = ClientAuthorizationUpdateApiFormRequest.builder();
    }

    public ClientAuthorizationUpdateApiFormRequestBuilder serviceId(@Nonnull String serviceId) {
        this.pojoBuilder.serviceId(serviceId);
        this._setterCalled = true;
        return this;
    }

    public ClientAuthorizationUpdateApiFormRequestBuilder clientId(@Nonnull String clientId) {
        this.pojoBuilder.clientId(clientId);
        this._setterCalled = true;
        return this;
    }

    public ClientAuthorizationUpdateApiFormRequestBuilder oneapi1Percent7BserviceIdPercent7D1client1authorization1update1Percent7BclientIdPercent7DPostRequestBodyContentApplication1jsonSchema(@Nullable 1api1Percent7BserviceIdPercent7D1client1authorization1update1Percent7BclientIdPercent7DPostRequestBodyContentApplication1jsonSchema oneapi1Percent7BserviceIdPercent7D1client1authorization1update1Percent7BclientIdPercent7DPostRequestBodyContentApplication1jsonSchema) {
        this.pojoBuilder.oneapi1Percent7BserviceIdPercent7D1client1authorization1update1Percent7BclientIdPercent7DPostRequestBodyContentApplication1jsonSchema(oneapi1Percent7BserviceIdPercent7D1client1authorization1update1Percent7BclientIdPercent7DPostRequestBodyContentApplication1jsonSchema);
        this._setterCalled = true;
        return this;
    }

    private ClientAuthorizationUpdateApiFormRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public ClientAuthorizationUpdateApiFormResponse call() throws Exception {
        RequestOperation<ClientAuthorizationUpdateApiFormRequest, ClientAuthorizationUpdateApiFormResponse> operation
              = new ClientAuthorizationUpdateApiFormOperation(sdkConfiguration);

        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
