/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum ClientRegistrationUpdateApiResponseMode {
    QUERY("QUERY"),
    FRAGMENT("FRAGMENT"),
    FORM_POST("FORM_POST"),
    JWT("JWT"),
    QUERY_JWT("QUERY_JWT"),
    FRAGMENT_JWT("FRAGMENT_JWT"),
    FORM_POST_JWT("FORM_POST_JWT");

    @JsonValue
    private final String value;

    ClientRegistrationUpdateApiResponseMode(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ClientRegistrationUpdateApiResponseMode> fromValue(String value) {
        for (ClientRegistrationUpdateApiResponseMode o: ClientRegistrationUpdateApiResponseMode.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

