/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.1api1Percent7BserviceIdPercent7D1device1verificationPostRequestBodyContentApplication1jsonSchema;
import org.openapis.openapi.operations.DeviceVerificationApiFormOperation;
import org.openapis.openapi.utils.Utils;

public class DeviceVerificationApiFormRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final DeviceVerificationApiFormRequest.Builder pojoBuilder;
    private DeviceVerificationApiFormRequest request;
    private boolean _setterCalled;

    public DeviceVerificationApiFormRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = DeviceVerificationApiFormRequest.builder();
    }

    public DeviceVerificationApiFormRequestBuilder serviceId(@Nonnull String serviceId) {
        this.pojoBuilder.serviceId(serviceId);
        this._setterCalled = true;
        return this;
    }

    public DeviceVerificationApiFormRequestBuilder oneapi1Percent7BserviceIdPercent7D1device1verificationPostRequestBodyContentApplication1jsonSchema(@Nonnull 1api1Percent7BserviceIdPercent7D1device1verificationPostRequestBodyContentApplication1jsonSchema oneapi1Percent7BserviceIdPercent7D1device1verificationPostRequestBodyContentApplication1jsonSchema) {
        this.pojoBuilder.oneapi1Percent7BserviceIdPercent7D1device1verificationPostRequestBodyContentApplication1jsonSchema(oneapi1Percent7BserviceIdPercent7D1device1verificationPostRequestBodyContentApplication1jsonSchema);
        this._setterCalled = true;
        return this;
    }

    private DeviceVerificationApiFormRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public DeviceVerificationApiFormResponse call() throws Exception {
        RequestOperation<DeviceVerificationApiFormRequest, DeviceVerificationApiFormResponse> operation
              = new DeviceVerificationApiFormOperation(sdkConfiguration);

        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
