/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.FederationRegistrationApiForm;
import org.openapis.openapi.utils.Utils;

public class FederationRegistrationApiFormRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final FederationRegistrationApiFormRequest.Builder pojoBuilder;
    private FederationRegistrationApiFormRequest request;
    private String serverURL;
    private boolean _setterCalled;

    public FederationRegistrationApiFormRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = FederationRegistrationApiFormRequest.builder();
    }

    public FederationRegistrationApiFormRequestBuilder serviceId(@Nonnull String serviceId) {
        this.pojoBuilder.serviceId(serviceId);
        this._setterCalled = true;
        return this;
    }

    public FederationRegistrationApiFormRequestBuilder requestBody(@Nonnull FederationRegistrationApiFormRequestBody requestBody) {
        this.pojoBuilder.requestBody(requestBody);
        this._setterCalled = true;
        return this;
    }

    public FederationRegistrationApiFormRequestBuilder serverURL(@Nullable String serverURL) {
        this.serverURL = serverURL;
        return this;
    }

    private FederationRegistrationApiFormRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public FederationRegistrationApiFormResponse call() throws Exception {
        RequestOperation<FederationRegistrationApiFormRequest, FederationRegistrationApiFormResponse> operation
              = new FederationRegistrationApiForm.Sync(sdkConfiguration, serverURL);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
