/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.GetApiServiceIdAuthAuthorizationTicketInfo;
import org.openapis.openapi.utils.Utils;

public class GetApiServiceIdAuthAuthorizationTicketInfoRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final GetApiServiceIdAuthAuthorizationTicketInfoRequest.Builder pojoBuilder;
    private GetApiServiceIdAuthAuthorizationTicketInfoRequest request;
    private String serverURL;
    private boolean _setterCalled;

    public GetApiServiceIdAuthAuthorizationTicketInfoRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = GetApiServiceIdAuthAuthorizationTicketInfoRequest.builder();
    }

    public GetApiServiceIdAuthAuthorizationTicketInfoRequestBuilder serviceId(@Nonnull String serviceId) {
        this.pojoBuilder.serviceId(serviceId);
        this._setterCalled = true;
        return this;
    }

    public GetApiServiceIdAuthAuthorizationTicketInfoRequestBuilder serverURL(@Nullable String serverURL) {
        this.serverURL = serverURL;
        return this;
    }

    private GetApiServiceIdAuthAuthorizationTicketInfoRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public GetApiServiceIdAuthAuthorizationTicketInfoResponse call() throws Exception {
        RequestOperation<GetApiServiceIdAuthAuthorizationTicketInfoRequest, GetApiServiceIdAuthAuthorizationTicketInfoResponse> operation
              = new GetApiServiceIdAuthAuthorizationTicketInfo.Sync(sdkConfiguration, serverURL);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
