/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;


public class GetApiServiceIdAuthAuthorizationTicketInfoResponseBody {
    /**
     * Information about the ticket.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("info")
    private String info;

    /**
     * The result of the `/auth/authorization/ticket/info` API call.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("action")
    private GetApiServiceIdAuthAuthorizationTicketInfoAction action;

    /**
     * The code which represents the result of the API call.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("resultCode")
    private String resultCode;

    /**
     * A short message which explains the result of the API call.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("resultMessage")
    private String resultMessage;

    @JsonCreator
    public GetApiServiceIdAuthAuthorizationTicketInfoResponseBody(
            @JsonProperty("info") @Nullable String info,
            @JsonProperty("action") @Nullable GetApiServiceIdAuthAuthorizationTicketInfoAction action,
            @JsonProperty("resultCode") @Nullable String resultCode,
            @JsonProperty("resultMessage") @Nullable String resultMessage) {
        this.info = info;
        this.action = action;
        this.resultCode = resultCode;
        this.resultMessage = resultMessage;
    }
    
    public GetApiServiceIdAuthAuthorizationTicketInfoResponseBody() {
        this(null, null, null,
            null);
    }

    /**
     * Information about the ticket.
     */
    public Optional<String> info() {
        return Optional.ofNullable(this.info);
    }

    /**
     * The result of the `/auth/authorization/ticket/info` API call.
     */
    public Optional<GetApiServiceIdAuthAuthorizationTicketInfoAction> action() {
        return Optional.ofNullable(this.action);
    }

    /**
     * The code which represents the result of the API call.
     */
    public Optional<String> resultCode() {
        return Optional.ofNullable(this.resultCode);
    }

    /**
     * A short message which explains the result of the API call.
     */
    public Optional<String> resultMessage() {
        return Optional.ofNullable(this.resultMessage);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Information about the ticket.
     */
    public GetApiServiceIdAuthAuthorizationTicketInfoResponseBody withInfo(@Nullable String info) {
        this.info = info;
        return this;
    }


    /**
     * The result of the `/auth/authorization/ticket/info` API call.
     */
    public GetApiServiceIdAuthAuthorizationTicketInfoResponseBody withAction(@Nullable GetApiServiceIdAuthAuthorizationTicketInfoAction action) {
        this.action = action;
        return this;
    }


    /**
     * The code which represents the result of the API call.
     */
    public GetApiServiceIdAuthAuthorizationTicketInfoResponseBody withResultCode(@Nullable String resultCode) {
        this.resultCode = resultCode;
        return this;
    }


    /**
     * A short message which explains the result of the API call.
     */
    public GetApiServiceIdAuthAuthorizationTicketInfoResponseBody withResultMessage(@Nullable String resultMessage) {
        this.resultMessage = resultMessage;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetApiServiceIdAuthAuthorizationTicketInfoResponseBody other = (GetApiServiceIdAuthAuthorizationTicketInfoResponseBody) o;
        return 
            Utils.enhancedDeepEquals(this.info, other.info) &&
            Utils.enhancedDeepEquals(this.action, other.action) &&
            Utils.enhancedDeepEquals(this.resultCode, other.resultCode) &&
            Utils.enhancedDeepEquals(this.resultMessage, other.resultMessage);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            info, action, resultCode,
            resultMessage);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetApiServiceIdAuthAuthorizationTicketInfoResponseBody.class,
                "info", info,
                "action", action,
                "resultCode", resultCode,
                "resultMessage", resultMessage);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String info;

        private GetApiServiceIdAuthAuthorizationTicketInfoAction action;

        private String resultCode;

        private String resultMessage;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Information about the ticket.
         */
        public Builder info(@Nullable String info) {
            this.info = info;
            return this;
        }

        /**
         * The result of the `/auth/authorization/ticket/info` API call.
         */
        public Builder action(@Nullable GetApiServiceIdAuthAuthorizationTicketInfoAction action) {
            this.action = action;
            return this;
        }

        /**
         * The code which represents the result of the API call.
         */
        public Builder resultCode(@Nullable String resultCode) {
            this.resultCode = resultCode;
            return this;
        }

        /**
         * A short message which explains the result of the API call.
         */
        public Builder resultMessage(@Nullable String resultMessage) {
            this.resultMessage = resultMessage;
            return this;
        }

        public GetApiServiceIdAuthAuthorizationTicketInfoResponseBody build() {
            return new GetApiServiceIdAuthAuthorizationTicketInfoResponseBody(
                info, action, resultCode,
                resultMessage);
        }

    }
}
