/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;


public class HskGetListApiResponseBody {
    /**
     * The code which represents the result of the API call.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("resultCode")
    private String resultCode;

    /**
     * A short message which explains the result of the API call.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("resultMessage")
    private String resultMessage;

    /**
     * Result of the API call
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("action")
    private HskGetListApiAction action;

    /**
     * List of HSK
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("hsks")
    private List<HskGetListApiHsk> hsks;

    @JsonCreator
    public HskGetListApiResponseBody(
            @JsonProperty("resultCode") @Nullable String resultCode,
            @JsonProperty("resultMessage") @Nullable String resultMessage,
            @JsonProperty("action") @Nullable HskGetListApiAction action,
            @JsonProperty("hsks") @Nullable List<HskGetListApiHsk> hsks) {
        this.resultCode = resultCode;
        this.resultMessage = resultMessage;
        this.action = action;
        this.hsks = hsks;
    }
    
    public HskGetListApiResponseBody() {
        this(null, null, null,
            null);
    }

    /**
     * The code which represents the result of the API call.
     */
    public Optional<String> resultCode() {
        return Optional.ofNullable(this.resultCode);
    }

    /**
     * A short message which explains the result of the API call.
     */
    public Optional<String> resultMessage() {
        return Optional.ofNullable(this.resultMessage);
    }

    /**
     * Result of the API call
     */
    public Optional<HskGetListApiAction> action() {
        return Optional.ofNullable(this.action);
    }

    /**
     * List of HSK
     */
    public Optional<List<HskGetListApiHsk>> hsks() {
        return Optional.ofNullable(this.hsks);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The code which represents the result of the API call.
     */
    public HskGetListApiResponseBody withResultCode(@Nullable String resultCode) {
        this.resultCode = resultCode;
        return this;
    }


    /**
     * A short message which explains the result of the API call.
     */
    public HskGetListApiResponseBody withResultMessage(@Nullable String resultMessage) {
        this.resultMessage = resultMessage;
        return this;
    }


    /**
     * Result of the API call
     */
    public HskGetListApiResponseBody withAction(@Nullable HskGetListApiAction action) {
        this.action = action;
        return this;
    }


    /**
     * List of HSK
     */
    public HskGetListApiResponseBody withHsks(@Nullable List<HskGetListApiHsk> hsks) {
        this.hsks = hsks;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        HskGetListApiResponseBody other = (HskGetListApiResponseBody) o;
        return 
            Utils.enhancedDeepEquals(this.resultCode, other.resultCode) &&
            Utils.enhancedDeepEquals(this.resultMessage, other.resultMessage) &&
            Utils.enhancedDeepEquals(this.action, other.action) &&
            Utils.enhancedDeepEquals(this.hsks, other.hsks);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            resultCode, resultMessage, action,
            hsks);
    }
    
    @Override
    public String toString() {
        return Utils.toString(HskGetListApiResponseBody.class,
                "resultCode", resultCode,
                "resultMessage", resultMessage,
                "action", action,
                "hsks", hsks);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String resultCode;

        private String resultMessage;

        private HskGetListApiAction action;

        private List<HskGetListApiHsk> hsks;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The code which represents the result of the API call.
         */
        public Builder resultCode(@Nullable String resultCode) {
            this.resultCode = resultCode;
            return this;
        }

        /**
         * A short message which explains the result of the API call.
         */
        public Builder resultMessage(@Nullable String resultMessage) {
            this.resultMessage = resultMessage;
            return this;
        }

        /**
         * Result of the API call
         */
        public Builder action(@Nullable HskGetListApiAction action) {
            this.action = action;
            return this;
        }

        /**
         * List of HSK
         */
        public Builder hsks(@Nullable List<HskGetListApiHsk> hsks) {
            this.hsks = hsks;
            return this;
        }

        public HskGetListApiResponseBody build() {
            return new HskGetListApiResponseBody(
                resultCode, resultMessage, action,
                hsks);
        }

    }
}
