/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class JoseVerifyApiRequest {
    /**
     * A service ID.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=serviceId")
    private String serviceId;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private JoseVerifyApiRequestBody requestBody;

    @JsonCreator
    public JoseVerifyApiRequest(
            @Nonnull String serviceId,
            @Nullable JoseVerifyApiRequestBody requestBody) {
        this.serviceId = Optional.ofNullable(serviceId)
            .orElseThrow(() -> new IllegalArgumentException("serviceId cannot be null"));
        this.requestBody = requestBody;
    }
    
    public JoseVerifyApiRequest(
            @Nonnull String serviceId) {
        this(serviceId, null);
    }

    /**
     * A service ID.
     */
    public String serviceId() {
        return this.serviceId;
    }

    public Optional<JoseVerifyApiRequestBody> requestBody() {
        return Optional.ofNullable(this.requestBody);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * A service ID.
     */
    public JoseVerifyApiRequest withServiceId(@Nonnull String serviceId) {
        this.serviceId = Utils.checkNotNull(serviceId, "serviceId");
        return this;
    }


    public JoseVerifyApiRequest withRequestBody(@Nullable JoseVerifyApiRequestBody requestBody) {
        this.requestBody = requestBody;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        JoseVerifyApiRequest other = (JoseVerifyApiRequest) o;
        return 
            Utils.enhancedDeepEquals(this.serviceId, other.serviceId) &&
            Utils.enhancedDeepEquals(this.requestBody, other.requestBody);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            serviceId, requestBody);
    }
    
    @Override
    public String toString() {
        return Utils.toString(JoseVerifyApiRequest.class,
                "serviceId", serviceId,
                "requestBody", requestBody);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String serviceId;

        private JoseVerifyApiRequestBody requestBody;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * A service ID.
         */
        public Builder serviceId(@Nonnull String serviceId) {
            this.serviceId = Utils.checkNotNull(serviceId, "serviceId");
            return this;
        }

        public Builder requestBody(@Nullable JoseVerifyApiRequestBody requestBody) {
            this.requestBody = requestBody;
            return this;
        }

        public JoseVerifyApiRequest build() {
            return new JoseVerifyApiRequest(
                serviceId, requestBody);
        }

    }
}
