/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.JoseVerifyApiForm;
import org.openapis.openapi.utils.Utils;

public class JoseVerifyApiFormRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final JoseVerifyApiFormRequest.Builder pojoBuilder;
    private JoseVerifyApiFormRequest request;
    private String serverURL;
    private boolean _setterCalled;

    public JoseVerifyApiFormRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = JoseVerifyApiFormRequest.builder();
    }

    public JoseVerifyApiFormRequestBuilder serviceId(@Nonnull String serviceId) {
        this.pojoBuilder.serviceId(serviceId);
        this._setterCalled = true;
        return this;
    }

    public JoseVerifyApiFormRequestBuilder requestBody(@Nullable JoseVerifyApiFormRequestBody requestBody) {
        this.pojoBuilder.requestBody(requestBody);
        this._setterCalled = true;
        return this;
    }

    public JoseVerifyApiFormRequestBuilder serverURL(@Nullable String serverURL) {
        this.serverURL = serverURL;
        return this;
    }

    private JoseVerifyApiFormRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public JoseVerifyApiFormResponse call() throws Exception {
        RequestOperation<JoseVerifyApiFormRequest, JoseVerifyApiFormResponse> operation
              = new JoseVerifyApiForm.Sync(sdkConfiguration, serverURL);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
