/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.models.components.1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class PushedAuthReqApiFormRequest {
    /**
     * A service ID.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=serviceId")
    private String serviceId;


    @SpeakeasyMetadata("request:mediaType=application/x-www-form-urlencoded")
    private 1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema 1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema;

    @JsonCreator
    public PushedAuthReqApiFormRequest(
            @Nonnull String serviceId,
            @Nonnull 1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema 1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema) {
        this.serviceId = Optional.ofNullable(serviceId)
            .orElseThrow(() -> new IllegalArgumentException("serviceId cannot be null"));
        this.1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema = Optional.ofNullable(1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema)
            .orElseThrow(() -> new IllegalArgumentException("1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema cannot be null"));
    }

    /**
     * A service ID.
     */
    public String serviceId() {
        return this.serviceId;
    }

    public 1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema 1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema() {
        return this.1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * A service ID.
     */
    public PushedAuthReqApiFormRequest withServiceId(@Nonnull String serviceId) {
        this.serviceId = Utils.checkNotNull(serviceId, "serviceId");
        return this;
    }


    public PushedAuthReqApiFormRequest with1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema(@Nonnull 1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema 1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema) {
        this.1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema = Utils.checkNotNull(1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema, "1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PushedAuthReqApiFormRequest other = (PushedAuthReqApiFormRequest) o;
        return 
            Utils.enhancedDeepEquals(this.serviceId, other.serviceId) &&
            Utils.enhancedDeepEquals(this.1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema, other.1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            serviceId, 1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PushedAuthReqApiFormRequest.class,
                "serviceId", serviceId,
                "1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema", 1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String serviceId;

        private 1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema 1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * A service ID.
         */
        public Builder serviceId(@Nonnull String serviceId) {
            this.serviceId = Utils.checkNotNull(serviceId, "serviceId");
            return this;
        }

        public Builder 1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema(@Nonnull 1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema 1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema) {
            this.1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema = Utils.checkNotNull(1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema, "1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema");
            return this;
        }

        public PushedAuthReqApiFormRequest build() {
            return new PushedAuthReqApiFormRequest(
                serviceId, 1api1Percent7BserviceIdPercent7D1pushedAuthReqPostRequestBodyContentApplication1jsonSchema);
        }

    }
}
