/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * ServiceCreateApiSupportedClientRegistrationTypeResponse
 * 
 * <p>Values for the `client_registration_types` RP metadata and the
 *  `client_registration_types_supported` OP metadata that are defined in
 *  [OpenID Connect Federation 1.0](https://openid.net/specs/openid-connect-federation-1_0.html).
 */
public enum ServiceCreateApiSupportedClientRegistrationTypeResponse {
    AUTOMATIC("AUTOMATIC"),
    EXPLICIT("EXPLICIT");

    @JsonValue
    private final String value;

    ServiceCreateApiSupportedClientRegistrationTypeResponse(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ServiceCreateApiSupportedClientRegistrationTypeResponse> fromValue(String value) {
        for (ServiceCreateApiSupportedClientRegistrationTypeResponse o: ServiceCreateApiSupportedClientRegistrationTypeResponse.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

