/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * ServiceUpdateApiSupportedDisplayResponse
 * 
 * <p>The display mode which the client application requests by `display` request parameter.
 * When the authorization request does not have `display` request parameter, `PAGE` is set as the default value.
 * 
 * <p>It is ensured that the value of `display` is one of the supported display modes which are specified
 * by `supportedDisplays` configuration parameter of the service. If the display mode specified by the
 * authorization request is not supported, an error is raised.
 * 
 * <p>Values for this property correspond to the values listed in
 * "[OpenID Connect Core 1.0, 3.1.2.1. Authentication Request](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest), display".
 */
public enum ServiceUpdateApiSupportedDisplayResponse {
    PAGE("PAGE"),
    POPUP("POPUP"),
    TOUCH("TOUCH"),
    WAP("WAP");

    @JsonValue
    private final String value;

    ServiceUpdateApiSupportedDisplayResponse(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ServiceUpdateApiSupportedDisplayResponse> fromValue(String value) {
        for (ServiceUpdateApiSupportedDisplayResponse o: ServiceUpdateApiSupportedDisplayResponse.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

