/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * ServiceUpdateApiUserCodeCharsetResponse
 * 
 * <p>The character set for end-user verification codes (`user_code`) for Device Flow.
 */
public enum ServiceUpdateApiUserCodeCharsetResponse {
    BASE20("BASE20"),
    NUMERIC("NUMERIC");

    @JsonValue
    private final String value;

    ServiceUpdateApiUserCodeCharsetResponse(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ServiceUpdateApiUserCodeCharsetResponse> fromValue(String value) {
        for (ServiceUpdateApiUserCodeCharsetResponse o: ServiceUpdateApiUserCodeCharsetResponse.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

