/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.models.components.ServiceInput;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class ServiceUpdateApiRequest {
    /**
     * A service ID.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=serviceId")
    private String serviceId;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private ServiceInput service;

    @JsonCreator
    public ServiceUpdateApiRequest(
            @Nonnull String serviceId,
            @Nullable ServiceInput service) {
        this.serviceId = Optional.ofNullable(serviceId)
            .orElseThrow(() -> new IllegalArgumentException("serviceId cannot be null"));
        this.service = service;
    }
    
    public ServiceUpdateApiRequest(
            @Nonnull String serviceId) {
        this(serviceId, null);
    }

    /**
     * A service ID.
     */
    public String serviceId() {
        return this.serviceId;
    }

    public Optional<ServiceInput> service() {
        return Optional.ofNullable(this.service);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * A service ID.
     */
    public ServiceUpdateApiRequest withServiceId(@Nonnull String serviceId) {
        this.serviceId = Utils.checkNotNull(serviceId, "serviceId");
        return this;
    }


    public ServiceUpdateApiRequest withService(@Nullable ServiceInput service) {
        this.service = service;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ServiceUpdateApiRequest other = (ServiceUpdateApiRequest) o;
        return 
            Utils.enhancedDeepEquals(this.serviceId, other.serviceId) &&
            Utils.enhancedDeepEquals(this.service, other.service);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            serviceId, service);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ServiceUpdateApiRequest.class,
                "serviceId", serviceId,
                "service", service);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String serviceId;

        private ServiceInput service;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * A service ID.
         */
        public Builder serviceId(@Nonnull String serviceId) {
            this.serviceId = Utils.checkNotNull(serviceId, "serviceId");
            return this;
        }

        public Builder service(@Nullable ServiceInput service) {
            this.service = service;
            return this;
        }

        public ServiceUpdateApiRequest build() {
            return new ServiceUpdateApiRequest(
                serviceId, service);
        }

    }
}
