/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nullable;
import java.lang.Exception;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.ServiceInput;
import org.openapis.openapi.operations.ServiceCreateApiOperation;

public class ServiceCreateApiRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private ServiceInput request;
    private boolean _setterCalled;

    public ServiceCreateApiRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ServiceCreateApiRequestBuilder request(@Nullable ServiceInput request) {
        this.request = request;
        return this;
    }

    private ServiceInput _buildRequest() {
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public ServiceCreateApiResponse call() throws Exception {
        RequestOperation<ServiceInput, ServiceCreateApiResponse> operation
              = new ServiceCreateApiOperation(sdkConfiguration);

        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
