/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum ServiceCreateApiSupportedClaimTypeRequest {
    NORMAL("NORMAL"),
    AGGREGATED("AGGREGATED"),
    DISTRIBUTED("DISTRIBUTED");

    @JsonValue
    private final String value;

    ServiceCreateApiSupportedClaimTypeRequest(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ServiceCreateApiSupportedClaimTypeRequest> fromValue(String value) {
        for (ServiceCreateApiSupportedClaimTypeRequest o: ServiceCreateApiSupportedClaimTypeRequest.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

