/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.models.components.1api1Percent7BserviceIdPercent7D1vci1batch1parsePostRequestBodyContentApplication1jsonSchema;
import org.openapis.openapi.operations.VciBatchParseApiFormOperation;
import org.openapis.openapi.utils.Utils;

public class VciBatchParseApiFormRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final VciBatchParseApiFormRequest.Builder pojoBuilder;
    private VciBatchParseApiFormRequest request;
    private boolean _setterCalled;

    public VciBatchParseApiFormRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = VciBatchParseApiFormRequest.builder();
    }

    public VciBatchParseApiFormRequestBuilder serviceId(@Nonnull String serviceId) {
        this.pojoBuilder.serviceId(serviceId);
        this._setterCalled = true;
        return this;
    }

    public VciBatchParseApiFormRequestBuilder oneapi1Percent7BserviceIdPercent7D1vci1batch1parsePostRequestBodyContentApplication1jsonSchema(@Nonnull 1api1Percent7BserviceIdPercent7D1vci1batch1parsePostRequestBodyContentApplication1jsonSchema oneapi1Percent7BserviceIdPercent7D1vci1batch1parsePostRequestBodyContentApplication1jsonSchema) {
        this.pojoBuilder.oneapi1Percent7BserviceIdPercent7D1vci1batch1parsePostRequestBodyContentApplication1jsonSchema(oneapi1Percent7BserviceIdPercent7D1vci1batch1parsePostRequestBodyContentApplication1jsonSchema);
        this._setterCalled = true;
        return this;
    }

    private VciBatchParseApiFormRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public VciBatchParseApiFormResponse call() throws Exception {
        RequestOperation<VciBatchParseApiFormRequest, VciBatchParseApiFormResponse> operation
              = new VciBatchParseApiFormOperation(sdkConfiguration);

        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
