/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.VciBatchParseApiForm;
import org.openapis.openapi.utils.Utils;

public class VciBatchParseApiFormRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final VciBatchParseApiFormRequest.Builder pojoBuilder;
    private VciBatchParseApiFormRequest request;
    private String serverURL;
    private boolean _setterCalled;

    public VciBatchParseApiFormRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = VciBatchParseApiFormRequest.builder();
    }

    public VciBatchParseApiFormRequestBuilder serviceId(@Nonnull String serviceId) {
        this.pojoBuilder.serviceId(serviceId);
        this._setterCalled = true;
        return this;
    }

    public VciBatchParseApiFormRequestBuilder requestBody(@Nonnull VciBatchParseApiFormRequestBody requestBody) {
        this.pojoBuilder.requestBody(requestBody);
        this._setterCalled = true;
        return this;
    }

    public VciBatchParseApiFormRequestBuilder serverURL(@Nullable String serverURL) {
        this.serverURL = serverURL;
        return this;
    }

    private VciBatchParseApiFormRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public VciBatchParseApiFormResponse call() throws Exception {
        RequestOperation<VciBatchParseApiFormRequest, VciBatchParseApiFormResponse> operation
              = new VciBatchParseApiForm.Sync(sdkConfiguration, serverURL);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
