/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.models.components.CredentialIssuanceOrder;
import org.openapis.openapi.utils.Utils;


public class VciDeferredIssueApiRequestBody {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("order")
    private CredentialIssuanceOrder order;

    @JsonCreator
    public VciDeferredIssueApiRequestBody(
            @JsonProperty("order") @Nullable CredentialIssuanceOrder order) {
        this.order = order;
    }
    
    public VciDeferredIssueApiRequestBody() {
        this(null);
    }

    public Optional<CredentialIssuanceOrder> order() {
        return Optional.ofNullable(this.order);
    }

    public static Builder builder() {
        return new Builder();
    }


    public VciDeferredIssueApiRequestBody withOrder(@Nullable CredentialIssuanceOrder order) {
        this.order = order;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VciDeferredIssueApiRequestBody other = (VciDeferredIssueApiRequestBody) o;
        return 
            Utils.enhancedDeepEquals(this.order, other.order);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            order);
    }
    
    @Override
    public String toString() {
        return Utils.toString(VciDeferredIssueApiRequestBody.class,
                "order", order);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private CredentialIssuanceOrder order;

        private Builder() {
          // force use of static builder() method
        }

        public Builder order(@Nullable CredentialIssuanceOrder order) {
            this.order = order;
            return this;
        }

        public VciDeferredIssueApiRequestBody build() {
            return new VciDeferredIssueApiRequestBody(
                order);
        }

    }
}
