/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * VciDeferredIssueApiAction
 * 
 * <p>The next action that the implementation of the deferred credential
 * endpoint should take.
 */
public enum VciDeferredIssueApiAction {
    OK("OK"),
    FORBIDDEN("FORBIDDEN"),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    CALLER_ERROR("CALLER_ERROR");

    @JsonValue
    private final String value;

    VciDeferredIssueApiAction(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<VciDeferredIssueApiAction> fromValue(String value) {
        for (VciDeferredIssueApiAction o: VciDeferredIssueApiAction.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

