/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.SDKConfiguration;
import org.openapis.openapi.operations.VciJwksApi;
import org.openapis.openapi.utils.Utils;

public class VciJwksApiRequestBuilder {
    private final SDKConfiguration sdkConfiguration;
    private final VciJwksApiRequest.Builder pojoBuilder;
    private VciJwksApiRequest request;
    private String serverURL;
    private boolean _setterCalled;

    public VciJwksApiRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.pojoBuilder = VciJwksApiRequest.builder();
    }

    public VciJwksApiRequestBuilder serviceId(@Nonnull String serviceId) {
        this.pojoBuilder.serviceId(serviceId);
        this._setterCalled = true;
        return this;
    }

    public VciJwksApiRequestBuilder requestBody(@Nonnull VciJwksApiRequestBody requestBody) {
        this.pojoBuilder.requestBody(requestBody);
        this._setterCalled = true;
        return this;
    }

    public VciJwksApiRequestBuilder serverURL(@Nullable String serverURL) {
        this.serverURL = serverURL;
        return this;
    }

    private VciJwksApiRequest _buildRequest() {
        if (this._setterCalled) {
            this.request = this.pojoBuilder.build();
        }
        return this.request;
    }
    /**
    * Executes the request and returns the response.
    *
    * @return The response from the server.
    */
    public VciJwksApiResponse call() throws Exception {
        RequestOperation<VciJwksApiRequest, VciJwksApiResponse> operation
              = new VciJwksApi.Sync(sdkConfiguration, serverURL);
        return operation.handleResponse(operation.doRequest(this._buildRequest()));
    }
}
