/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;


public class VciJwtissuerApiResponseBody {
    /**
     * The code which represents the result of the API call.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("resultCode")
    private String resultCode;

    /**
     * A short message which explains the result of the API call.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("resultMessage")
    private String resultMessage;

    /**
     * The next action that the implementation of the JWT issuer metadata
     * endpoint (`/.well-known/jwt-issuer`) should take after getting
     * a response from Authlete's `/vci/jwtissuer` API.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("action")
    private VciJwtissuerApiAction action;

    /**
     * Get the content that the implementation of the credential issuer
     * metadata endpoint should use when it constructs a response.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("responseContent")
    private String responseContent;

    @JsonCreator
    public VciJwtissuerApiResponseBody(
            @JsonProperty("resultCode") @Nullable String resultCode,
            @JsonProperty("resultMessage") @Nullable String resultMessage,
            @JsonProperty("action") @Nullable VciJwtissuerApiAction action,
            @JsonProperty("responseContent") @Nullable String responseContent) {
        this.resultCode = resultCode;
        this.resultMessage = resultMessage;
        this.action = action;
        this.responseContent = responseContent;
    }
    
    public VciJwtissuerApiResponseBody() {
        this(null, null, null,
            null);
    }

    /**
     * The code which represents the result of the API call.
     */
    public Optional<String> resultCode() {
        return Optional.ofNullable(this.resultCode);
    }

    /**
     * A short message which explains the result of the API call.
     */
    public Optional<String> resultMessage() {
        return Optional.ofNullable(this.resultMessage);
    }

    /**
     * The next action that the implementation of the JWT issuer metadata
     * endpoint (`/.well-known/jwt-issuer`) should take after getting
     * a response from Authlete's `/vci/jwtissuer` API.
     */
    public Optional<VciJwtissuerApiAction> action() {
        return Optional.ofNullable(this.action);
    }

    /**
     * Get the content that the implementation of the credential issuer
     * metadata endpoint should use when it constructs a response.
     */
    public Optional<String> responseContent() {
        return Optional.ofNullable(this.responseContent);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The code which represents the result of the API call.
     */
    public VciJwtissuerApiResponseBody withResultCode(@Nullable String resultCode) {
        this.resultCode = resultCode;
        return this;
    }


    /**
     * A short message which explains the result of the API call.
     */
    public VciJwtissuerApiResponseBody withResultMessage(@Nullable String resultMessage) {
        this.resultMessage = resultMessage;
        return this;
    }


    /**
     * The next action that the implementation of the JWT issuer metadata
     * endpoint (`/.well-known/jwt-issuer`) should take after getting
     * a response from Authlete's `/vci/jwtissuer` API.
     */
    public VciJwtissuerApiResponseBody withAction(@Nullable VciJwtissuerApiAction action) {
        this.action = action;
        return this;
    }


    /**
     * Get the content that the implementation of the credential issuer
     * metadata endpoint should use when it constructs a response.
     */
    public VciJwtissuerApiResponseBody withResponseContent(@Nullable String responseContent) {
        this.responseContent = responseContent;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VciJwtissuerApiResponseBody other = (VciJwtissuerApiResponseBody) o;
        return 
            Utils.enhancedDeepEquals(this.resultCode, other.resultCode) &&
            Utils.enhancedDeepEquals(this.resultMessage, other.resultMessage) &&
            Utils.enhancedDeepEquals(this.action, other.action) &&
            Utils.enhancedDeepEquals(this.responseContent, other.responseContent);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            resultCode, resultMessage, action,
            responseContent);
    }
    
    @Override
    public String toString() {
        return Utils.toString(VciJwtissuerApiResponseBody.class,
                "resultCode", resultCode,
                "resultMessage", resultMessage,
                "action", action,
                "responseContent", responseContent);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String resultCode;

        private String resultMessage;

        private VciJwtissuerApiAction action;

        private String responseContent;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The code which represents the result of the API call.
         */
        public Builder resultCode(@Nullable String resultCode) {
            this.resultCode = resultCode;
            return this;
        }

        /**
         * A short message which explains the result of the API call.
         */
        public Builder resultMessage(@Nullable String resultMessage) {
            this.resultMessage = resultMessage;
            return this;
        }

        /**
         * The next action that the implementation of the JWT issuer metadata
         * endpoint (`/.well-known/jwt-issuer`) should take after getting
         * a response from Authlete's `/vci/jwtissuer` API.
         */
        public Builder action(@Nullable VciJwtissuerApiAction action) {
            this.action = action;
            return this;
        }

        /**
         * Get the content that the implementation of the credential issuer
         * metadata endpoint should use when it constructs a response.
         */
        public Builder responseContent(@Nullable String responseContent) {
            this.responseContent = responseContent;
            return this;
        }

        public VciJwtissuerApiResponseBody build() {
            return new VciJwtissuerApiResponseBody(
                resultCode, resultMessage, action,
                responseContent);
        }

    }
}
