/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.models.components.CredentialRequestInfo;
import org.openapis.openapi.utils.Utils;


public class VciSingleParseApiFormResponseBody {
    /**
     * The code which represents the result of the API call.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("resultCode")
    private String resultCode;

    /**
     * A short message which explains the result of the API call.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("resultMessage")
    private String resultMessage;

    /**
     * The next action that the credential endpoint should take.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("action")
    private VciSingleParseApiFormAction action;

    /**
     * The content of the response to the request sender.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("responseContent")
    private String responseContent;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("info")
    private CredentialRequestInfo info;

    @JsonCreator
    public VciSingleParseApiFormResponseBody(
            @JsonProperty("resultCode") @Nullable String resultCode,
            @JsonProperty("resultMessage") @Nullable String resultMessage,
            @JsonProperty("action") @Nullable VciSingleParseApiFormAction action,
            @JsonProperty("responseContent") @Nullable String responseContent,
            @JsonProperty("info") @Nullable CredentialRequestInfo info) {
        this.resultCode = resultCode;
        this.resultMessage = resultMessage;
        this.action = action;
        this.responseContent = responseContent;
        this.info = info;
    }
    
    public VciSingleParseApiFormResponseBody() {
        this(null, null, null,
            null, null);
    }

    /**
     * The code which represents the result of the API call.
     */
    public Optional<String> resultCode() {
        return Optional.ofNullable(this.resultCode);
    }

    /**
     * A short message which explains the result of the API call.
     */
    public Optional<String> resultMessage() {
        return Optional.ofNullable(this.resultMessage);
    }

    /**
     * The next action that the credential endpoint should take.
     */
    public Optional<VciSingleParseApiFormAction> action() {
        return Optional.ofNullable(this.action);
    }

    /**
     * The content of the response to the request sender.
     */
    public Optional<String> responseContent() {
        return Optional.ofNullable(this.responseContent);
    }

    public Optional<CredentialRequestInfo> info() {
        return Optional.ofNullable(this.info);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The code which represents the result of the API call.
     */
    public VciSingleParseApiFormResponseBody withResultCode(@Nullable String resultCode) {
        this.resultCode = resultCode;
        return this;
    }


    /**
     * A short message which explains the result of the API call.
     */
    public VciSingleParseApiFormResponseBody withResultMessage(@Nullable String resultMessage) {
        this.resultMessage = resultMessage;
        return this;
    }


    /**
     * The next action that the credential endpoint should take.
     */
    public VciSingleParseApiFormResponseBody withAction(@Nullable VciSingleParseApiFormAction action) {
        this.action = action;
        return this;
    }


    /**
     * The content of the response to the request sender.
     */
    public VciSingleParseApiFormResponseBody withResponseContent(@Nullable String responseContent) {
        this.responseContent = responseContent;
        return this;
    }


    public VciSingleParseApiFormResponseBody withInfo(@Nullable CredentialRequestInfo info) {
        this.info = info;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VciSingleParseApiFormResponseBody other = (VciSingleParseApiFormResponseBody) o;
        return 
            Utils.enhancedDeepEquals(this.resultCode, other.resultCode) &&
            Utils.enhancedDeepEquals(this.resultMessage, other.resultMessage) &&
            Utils.enhancedDeepEquals(this.action, other.action) &&
            Utils.enhancedDeepEquals(this.responseContent, other.responseContent) &&
            Utils.enhancedDeepEquals(this.info, other.info);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            resultCode, resultMessage, action,
            responseContent, info);
    }
    
    @Override
    public String toString() {
        return Utils.toString(VciSingleParseApiFormResponseBody.class,
                "resultCode", resultCode,
                "resultMessage", resultMessage,
                "action", action,
                "responseContent", responseContent,
                "info", info);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String resultCode;

        private String resultMessage;

        private VciSingleParseApiFormAction action;

        private String responseContent;

        private CredentialRequestInfo info;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The code which represents the result of the API call.
         */
        public Builder resultCode(@Nullable String resultCode) {
            this.resultCode = resultCode;
            return this;
        }

        /**
         * A short message which explains the result of the API call.
         */
        public Builder resultMessage(@Nullable String resultMessage) {
            this.resultMessage = resultMessage;
            return this;
        }

        /**
         * The next action that the credential endpoint should take.
         */
        public Builder action(@Nullable VciSingleParseApiFormAction action) {
            this.action = action;
            return this;
        }

        /**
         * The content of the response to the request sender.
         */
        public Builder responseContent(@Nullable String responseContent) {
            this.responseContent = responseContent;
            return this;
        }

        public Builder info(@Nullable CredentialRequestInfo info) {
            this.info = info;
            return this;
        }

        public VciSingleParseApiFormResponseBody build() {
            return new VciSingleParseApiFormResponseBody(
                resultCode, resultMessage, action,
                responseContent, info);
        }

    }
}
