/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.models.operations.VciBatchIssueApiRequest;
import org.openapis.openapi.models.operations.VciBatchIssueApiRequestBody;
import org.openapis.openapi.models.operations.VciBatchIssueApiRequestBuilder;
import org.openapis.openapi.models.operations.VciBatchIssueApiResponse;
import org.openapis.openapi.models.operations.VciJwtissuerApiFormRequest;
import org.openapis.openapi.models.operations.VciJwtissuerApiFormRequestBody;
import org.openapis.openapi.models.operations.VciJwtissuerApiFormRequestBuilder;
import org.openapis.openapi.models.operations.VciJwtissuerApiFormResponse;
import org.openapis.openapi.models.operations.VciJwtissuerApiRequest;
import org.openapis.openapi.models.operations.VciJwtissuerApiRequestBody;
import org.openapis.openapi.models.operations.VciJwtissuerApiRequestBuilder;
import org.openapis.openapi.models.operations.VciJwtissuerApiResponse;
import org.openapis.openapi.operations.VciBatchIssueApi;
import org.openapis.openapi.operations.VciJwtissuerApi;
import org.openapis.openapi.operations.VciJwtissuerApiForm;


public class Credentials {
    private final SDKConfiguration sdkConfiguration;

    Credentials(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    /**
     * /api/{serviceId}/vci/jwtissuer API
     * 
     * @return The call builder
     */
    public VciJwtissuerApiRequestBuilder issueJwt() {
        return new VciJwtissuerApiRequestBuilder(sdkConfiguration);
    }

    /**
     * /api/{serviceId}/vci/jwtissuer API
     * 
     * @param serviceId A service ID.
     * @param requestBody 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public VciJwtissuerApiResponse issueJwt(@Nonnull String serviceId, @Nonnull VciJwtissuerApiRequestBody requestBody) throws Exception {
        return issueJwt(serviceId, requestBody, null);
    }

    /**
     * /api/{serviceId}/vci/jwtissuer API
     * 
     * @param serviceId A service ID.
     * @param requestBody 
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public VciJwtissuerApiResponse issueJwt(
            @Nonnull String serviceId, @Nonnull VciJwtissuerApiRequestBody requestBody,
            @Nullable String serverURL) throws Exception {
        VciJwtissuerApiRequest request = new VciJwtissuerApiRequest(serviceId, requestBody);
        RequestOperation<VciJwtissuerApiRequest, VciJwtissuerApiResponse> operation
              = new VciJwtissuerApi.Sync(sdkConfiguration, serverURL);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * /api/{serviceId}/vci/jwtissuer API
     * 
     * @return The call builder
     */
    public VciJwtissuerApiFormRequestBuilder issueJwtForm() {
        return new VciJwtissuerApiFormRequestBuilder(sdkConfiguration);
    }

    /**
     * /api/{serviceId}/vci/jwtissuer API
     * 
     * @param serviceId A service ID.
     * @param requestBody 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public VciJwtissuerApiFormResponse issueJwtForm(@Nonnull String serviceId, @Nonnull VciJwtissuerApiFormRequestBody requestBody) throws Exception {
        return issueJwtForm(serviceId, requestBody, null);
    }

    /**
     * /api/{serviceId}/vci/jwtissuer API
     * 
     * @param serviceId A service ID.
     * @param requestBody 
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public VciJwtissuerApiFormResponse issueJwtForm(
            @Nonnull String serviceId, @Nonnull VciJwtissuerApiFormRequestBody requestBody,
            @Nullable String serverURL) throws Exception {
        VciJwtissuerApiFormRequest request = new VciJwtissuerApiFormRequest(serviceId, requestBody);
        RequestOperation<VciJwtissuerApiFormRequest, VciJwtissuerApiFormResponse> operation
              = new VciJwtissuerApiForm.Sync(sdkConfiguration, serverURL);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * /api/{serviceId}/vci/batch/issue API
     * 
     * @return The call builder
     */
    public VciBatchIssueApiRequestBuilder issueBatch() {
        return new VciBatchIssueApiRequestBuilder(sdkConfiguration);
    }

    /**
     * /api/{serviceId}/vci/batch/issue API
     * 
     * @param serviceId A service ID.
     * @param requestBody 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public VciBatchIssueApiResponse issueBatch(@Nonnull String serviceId, @Nonnull VciBatchIssueApiRequestBody requestBody) throws Exception {
        return issueBatch(serviceId, requestBody, null);
    }

    /**
     * /api/{serviceId}/vci/batch/issue API
     * 
     * @param serviceId A service ID.
     * @param requestBody 
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public VciBatchIssueApiResponse issueBatch(
            @Nonnull String serviceId, @Nonnull VciBatchIssueApiRequestBody requestBody,
            @Nullable String serverURL) throws Exception {
        VciBatchIssueApiRequest request = new VciBatchIssueApiRequest(serviceId, requestBody);
        RequestOperation<VciBatchIssueApiRequest, VciBatchIssueApiResponse> operation
              = new VciBatchIssueApi.Sync(sdkConfiguration, serverURL);
        return operation.handleResponse(operation.doRequest(request));
    }

}
