/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.models.operations.HskCreateApiFormRequest;
import org.openapis.openapi.models.operations.HskCreateApiFormRequestBody;
import org.openapis.openapi.models.operations.HskCreateApiFormRequestBuilder;
import org.openapis.openapi.models.operations.HskCreateApiFormResponse;
import org.openapis.openapi.models.operations.HskCreateApiRequest;
import org.openapis.openapi.models.operations.HskCreateApiRequestBody;
import org.openapis.openapi.models.operations.HskCreateApiRequestBuilder;
import org.openapis.openapi.models.operations.HskCreateApiResponse;
import org.openapis.openapi.models.operations.HskGetListApiRequest;
import org.openapis.openapi.models.operations.HskGetListApiRequestBuilder;
import org.openapis.openapi.models.operations.HskGetListApiResponse;
import org.openapis.openapi.operations.HskCreateApi;
import org.openapis.openapi.operations.HskCreateApiForm;
import org.openapis.openapi.operations.HskGetListApi;


public class HardwareSecurityKeys {
    private final SDKConfiguration sdkConfiguration;

    HardwareSecurityKeys(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    /**
     * Create Security Key
     * 
     * @return The call builder
     */
    public HskCreateApiRequestBuilder create() {
        return new HskCreateApiRequestBuilder(sdkConfiguration);
    }

    /**
     * Create Security Key
     * 
     * @param serviceId A service ID.
     * @param requestBody 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public HskCreateApiResponse create(@Nonnull String serviceId, @Nonnull HskCreateApiRequestBody requestBody) throws Exception {
        return create(serviceId, requestBody, null);
    }

    /**
     * Create Security Key
     * 
     * @param serviceId A service ID.
     * @param requestBody 
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public HskCreateApiResponse create(
            @Nonnull String serviceId, @Nonnull HskCreateApiRequestBody requestBody,
            @Nullable String serverURL) throws Exception {
        HskCreateApiRequest request = new HskCreateApiRequest(serviceId, requestBody);
        RequestOperation<HskCreateApiRequest, HskCreateApiResponse> operation
              = new HskCreateApi.Sync(sdkConfiguration, serverURL);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Create Security Key
     * 
     * @return The call builder
     */
    public HskCreateApiFormRequestBuilder createForm() {
        return new HskCreateApiFormRequestBuilder(sdkConfiguration);
    }

    /**
     * Create Security Key
     * 
     * @param serviceId A service ID.
     * @param requestBody 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public HskCreateApiFormResponse createForm(@Nonnull String serviceId, @Nonnull HskCreateApiFormRequestBody requestBody) throws Exception {
        return createForm(serviceId, requestBody, null);
    }

    /**
     * Create Security Key
     * 
     * @param serviceId A service ID.
     * @param requestBody 
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public HskCreateApiFormResponse createForm(
            @Nonnull String serviceId, @Nonnull HskCreateApiFormRequestBody requestBody,
            @Nullable String serverURL) throws Exception {
        HskCreateApiFormRequest request = new HskCreateApiFormRequest(serviceId, requestBody);
        RequestOperation<HskCreateApiFormRequest, HskCreateApiFormResponse> operation
              = new HskCreateApiForm.Sync(sdkConfiguration, serverURL);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List Security Keys
     * 
     * @return The call builder
     */
    public HskGetListApiRequestBuilder list() {
        return new HskGetListApiRequestBuilder(sdkConfiguration);
    }

    /**
     * List Security Keys
     * 
     * @param serviceId A service ID.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public HskGetListApiResponse list(@Nonnull String serviceId) throws Exception {
        return list(serviceId, null);
    }

    /**
     * List Security Keys
     * 
     * @param serviceId A service ID.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public HskGetListApiResponse list(@Nonnull String serviceId, @Nullable String serverURL) throws Exception {
        HskGetListApiRequest request = new HskGetListApiRequest(serviceId);
        RequestOperation<HskGetListApiRequest, HskGetListApiResponse> operation
              = new HskGetListApi.Sync(sdkConfiguration, serverURL);
        return operation.handleResponse(operation.doRequest(request));
    }

}
