/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Boolean;
import java.lang.Exception;
import java.lang.Integer;
import java.lang.String;
import org.openapis.openapi.models.operations.ServiceConfigurationApiRequest;
import org.openapis.openapi.models.operations.ServiceConfigurationApiRequestBuilder;
import org.openapis.openapi.models.operations.ServiceConfigurationApiResponse;
import org.openapis.openapi.models.operations.ServiceGetApiRequest;
import org.openapis.openapi.models.operations.ServiceGetApiRequestBuilder;
import org.openapis.openapi.models.operations.ServiceGetApiResponse;
import org.openapis.openapi.models.operations.ServiceGetListApiRequest;
import org.openapis.openapi.models.operations.ServiceGetListApiRequestBuilder;
import org.openapis.openapi.models.operations.ServiceGetListApiResponse;
import org.openapis.openapi.operations.ServiceConfigurationApiOperation;
import org.openapis.openapi.operations.ServiceGetApiOperation;
import org.openapis.openapi.operations.ServiceGetListApiOperation;


public class ServiceManagement {
    private final SDKConfiguration sdkConfiguration;

    ServiceManagement(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    /**
     * Get Service
     * 
     * <p>Get a service.
     * 
     * <p>If the access token can only view or modify clients underneath this service, but does not
     * have access to view this service directly, a limited view of the service will be returned.
     * 
     * @return The call builder
     */
    public ServiceGetApiRequestBuilder get() {
        return new ServiceGetApiRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Service
     * 
     * <p>Get a service.
     * 
     * <p>If the access token can only view or modify clients underneath this service, but does not
     * have access to view this service directly, a limited view of the service will be returned.
     * 
     * @param serviceId A service ID.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public ServiceGetApiResponse get(@Nonnull String serviceId) throws Exception {
        ServiceGetApiRequest request = new ServiceGetApiRequest(serviceId);
        RequestOperation<ServiceGetApiRequest, ServiceGetApiResponse> operation
              = new ServiceGetApiOperation(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List Services
     * 
     * <p>Get a list of services.
     * 
     * <p>If the access token can only view or modify clients underneath a service, but does not
     * have access to view that service directly, a limited view of the service will be returned.
     * Otherwise, all properties of the service are returned.
     * 
     * <p>If the access token is an administrative token, this returns a list of all services on the Authlete instance.
     * Otherwise, all services that the access token can view, even in a limited fashion, are returned.
     * 
     * @return The call builder
     */
    public ServiceGetListApiRequestBuilder list() {
        return new ServiceGetListApiRequestBuilder(sdkConfiguration);
    }

    /**
     * List Services
     * 
     * <p>Get a list of services.
     * 
     * <p>If the access token can only view or modify clients underneath a service, but does not
     * have access to view that service directly, a limited view of the service will be returned.
     * Otherwise, all properties of the service are returned.
     * 
     * <p>If the access token is an administrative token, this returns a list of all services on the Authlete instance.
     * Otherwise, all services that the access token can view, even in a limited fashion, are returned.
     * 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public ServiceGetListApiResponse listDirect() throws Exception {
        return list(null, null);
    }

    /**
     * List Services
     * 
     * <p>Get a list of services.
     * 
     * <p>If the access token can only view or modify clients underneath a service, but does not
     * have access to view that service directly, a limited view of the service will be returned.
     * Otherwise, all properties of the service are returned.
     * 
     * <p>If the access token is an administrative token, this returns a list of all services on the Authlete instance.
     * Otherwise, all services that the access token can view, even in a limited fashion, are returned.
     * 
     * @param start Start index (inclusive) of the result set. The default value is 0. Must not be a negative number.
     * @param end End index (exclusive) of the result set. The default value is 5. Must not be a negative number.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public ServiceGetListApiResponse list(@Nullable Integer start, @Nullable Integer end) throws Exception {
        ServiceGetListApiRequest request = new ServiceGetListApiRequest(start, end);
        RequestOperation<ServiceGetListApiRequest, ServiceGetListApiResponse> operation
              = new ServiceGetListApiOperation(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get Service Configuration
     * 
     * <p>This API gathers configuration information about a service.
     * 
     * <p>&lt;br&gt;
     * &lt;details&gt;
     * &lt;summary&gt;Description&lt;/summary&gt;
     * 
     * <p>This API is supposed to be called from within the implementation of the configuration endpoint of
     * the service where the service that supports OpenID Connect and [OpenID Connect Discovery 1.0](https://openid.net/specs/openid-connect-discovery-1_0.html)
     * must expose its configuration information in a JSON format. Details about the format are described
     * in "[3. OpenID Provider Metadata](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata)"
     * in OpenID Connect Discovery 1.0.
     * 
     * <p>&lt;/details&gt;
     * 
     * @return The call builder
     */
    public ServiceConfigurationApiRequestBuilder getConfiguration() {
        return new ServiceConfigurationApiRequestBuilder(sdkConfiguration);
    }

    /**
     * Get Service Configuration
     * 
     * <p>This API gathers configuration information about a service.
     * 
     * <p>&lt;br&gt;
     * &lt;details&gt;
     * &lt;summary&gt;Description&lt;/summary&gt;
     * 
     * <p>This API is supposed to be called from within the implementation of the configuration endpoint of
     * the service where the service that supports OpenID Connect and [OpenID Connect Discovery 1.0](https://openid.net/specs/openid-connect-discovery-1_0.html)
     * must expose its configuration information in a JSON format. Details about the format are described
     * in "[3. OpenID Provider Metadata](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata)"
     * in OpenID Connect Discovery 1.0.
     * 
     * <p>&lt;/details&gt;
     * 
     * @param serviceId A service ID.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public ServiceConfigurationApiResponse getConfiguration(@Nonnull String serviceId) throws Exception {
        return getConfiguration(serviceId, null, null);
    }

    /**
     * Get Service Configuration
     * 
     * <p>This API gathers configuration information about a service.
     * 
     * <p>&lt;br&gt;
     * &lt;details&gt;
     * &lt;summary&gt;Description&lt;/summary&gt;
     * 
     * <p>This API is supposed to be called from within the implementation of the configuration endpoint of
     * the service where the service that supports OpenID Connect and [OpenID Connect Discovery 1.0](https://openid.net/specs/openid-connect-discovery-1_0.html)
     * must expose its configuration information in a JSON format. Details about the format are described
     * in "[3. OpenID Provider Metadata](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata)"
     * in OpenID Connect Discovery 1.0.
     * 
     * <p>&lt;/details&gt;
     * 
     * @param serviceId A service ID.
     * @param pretty This boolean value indicates whether the JSON in the response should be formatted or not. If `true`, the JSON in the response is pretty-formatted. The default value is `false`.
     * @param patch Get the JSON Patch [RFC 6902 JavaScript Object Notation (JSON) Patch](https://www.rfc-editor.org/rfc/rfc6902) to be applied.
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public ServiceConfigurationApiResponse getConfiguration(
            @Nonnull String serviceId, @Nullable Boolean pretty,
            @Nullable String patch) throws Exception {
        ServiceConfigurationApiRequest request = new ServiceConfigurationApiRequest(serviceId, pretty, patch);
        RequestOperation<ServiceConfigurationApiRequest, ServiceConfigurationApiResponse> operation
              = new ServiceConfigurationApiOperation(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(request));
    }

}
