/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi;

import static org.openapis.openapi.operations.Operations.RequestOperation;

import jakarta.annotation.Nonnull;
import java.lang.Exception;
import java.lang.String;
import org.openapis.openapi.models.components.1api1Percent7BserviceIdPercent7D1vci1single1parsePostRequestBodyContentApplication1jsonSchema;
import org.openapis.openapi.models.operations.VciSingleParseApiFormRequest;
import org.openapis.openapi.models.operations.VciSingleParseApiFormRequestBuilder;
import org.openapis.openapi.models.operations.VciSingleParseApiFormResponse;
import org.openapis.openapi.models.operations.VciSingleParseApiRequest;
import org.openapis.openapi.models.operations.VciSingleParseApiRequestBody;
import org.openapis.openapi.models.operations.VciSingleParseApiRequestBuilder;
import org.openapis.openapi.models.operations.VciSingleParseApiResponse;
import org.openapis.openapi.operations.VciSingleParseApiFormOperation;
import org.openapis.openapi.operations.VciSingleParseApiOperation;


public class Vci {
    private final SDKConfiguration sdkConfiguration;

    Vci(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    /**
     * /api/{serviceId}/vci/single/parse API
     * 
     * <p>null
     * 
     * @return The call builder
     */
    public VciSingleParseApiRequestBuilder parseSingle() {
        return new VciSingleParseApiRequestBuilder(sdkConfiguration);
    }

    /**
     * /api/{serviceId}/vci/single/parse API
     * 
     * <p>null
     * 
     * @param serviceId A service ID.
     * @param requestBody 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public VciSingleParseApiResponse parseSingle(@Nonnull String serviceId, @Nonnull VciSingleParseApiRequestBody requestBody) throws Exception {
        VciSingleParseApiRequest request = new VciSingleParseApiRequest(serviceId, requestBody);
        RequestOperation<VciSingleParseApiRequest, VciSingleParseApiResponse> operation
              = new VciSingleParseApiOperation(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * /api/{serviceId}/vci/single/parse API
     * 
     * <p>null
     * 
     * @return The call builder
     */
    public VciSingleParseApiFormRequestBuilder parseSingleForm() {
        return new VciSingleParseApiFormRequestBuilder(sdkConfiguration);
    }

    /**
     * /api/{serviceId}/vci/single/parse API
     * 
     * <p>null
     * 
     * @param serviceId A service ID.
     * @param 1api1Percent7BserviceIdPercent7D1vci1single1parsePostRequestBodyContentApplication1jsonSchema 
     * @return The response from the API call
     * @throws Exception if the API call fails
     */
    public VciSingleParseApiFormResponse parseSingleForm(@Nonnull String serviceId, @Nonnull 1api1Percent7BserviceIdPercent7D1vci1single1parsePostRequestBodyContentApplication1jsonSchema 1api1Percent7BserviceIdPercent7D1vci1single1parsePostRequestBodyContentApplication1jsonSchema) throws Exception {
        VciSingleParseApiFormRequest request = new VciSingleParseApiFormRequest(serviceId, 1api1Percent7BserviceIdPercent7D1vci1single1parsePostRequestBodyContentApplication1jsonSchema);
        RequestOperation<VciSingleParseApiFormRequest, VciSingleParseApiFormResponse> operation
              = new VciSingleParseApiFormOperation(sdkConfiguration);
        return operation.handleResponse(operation.doRequest(request));
    }

}
