/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreatePlanetJsonResponse = components.Planet | Uint8Array | string;

/** @internal */
export const CreatePlanetJsonResponse$inboundSchema: z.ZodType<
  CreatePlanetJsonResponse,
  z.ZodTypeDef,
  unknown
> = z.union([components.Planet$inboundSchema, b64$.zodInbound]);

/** @internal */
export type CreatePlanetJsonResponse$Outbound =
  | components.Planet$Outbound
  | Uint8Array;

/** @internal */
export const CreatePlanetJsonResponse$outboundSchema: z.ZodType<
  CreatePlanetJsonResponse$Outbound,
  z.ZodTypeDef,
  CreatePlanetJsonResponse
> = z.union([components.Planet$outboundSchema, b64$.zodOutbound]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreatePlanetJsonResponse$ {
  /** @deprecated use `CreatePlanetJsonResponse$inboundSchema` instead. */
  export const inboundSchema = CreatePlanetJsonResponse$inboundSchema;
  /** @deprecated use `CreatePlanetJsonResponse$outboundSchema` instead. */
  export const outboundSchema = CreatePlanetJsonResponse$outboundSchema;
  /** @deprecated use `CreatePlanetJsonResponse$Outbound` instead. */
  export type Outbound = CreatePlanetJsonResponse$Outbound;
}

export function createPlanetJsonResponseToJSON(
  createPlanetJsonResponse: CreatePlanetJsonResponse,
): string {
  return JSON.stringify(
    CreatePlanetJsonResponse$outboundSchema.parse(createPlanetJsonResponse),
  );
}

export function createPlanetJsonResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreatePlanetJsonResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePlanetJsonResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePlanetJsonResponse' from JSON`,
  );
}
