/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public enum ItemsFapiModes {
    FAPI1_ADVANCED("FAPI1_ADVANCED"),
    FAPI1_BASELINE("FAPI1_BASELINE"),
    FAPI2_MESSAGE_SIGNING_AUTH_REQ("FAPI2_MESSAGE_SIGNING_AUTH_REQ"),
    FAPI2_MESSAGE_SIGNING_AUTH_RES("FAPI2_MESSAGE_SIGNING_AUTH_RES"),
    FAPI2_MESSAGE_SIGNING_INTROSPECTION_RES("FAPI2_MESSAGE_SIGNING_INTROSPECTION_RES"),
    FAPI2_SECURITY("FAPI2_SECURITY");

    @JsonValue
    private final String value;

    ItemsFapiModes(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<ItemsFapiModes> fromValue(String value) {
        for (ItemsFapiModes o: ItemsFapiModes.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

