/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class 1api1Percent7BserviceIdPercent7D1client1authorization1update1Percent7BclientIdPercent7DPostRequestBodyContentApplication1jsonSchema {
    /**
     * The subject (= unique identifier) of the end-user who has granted authorization to the client
     * application.
     */
    @SpeakeasyMetadata("form:name=subject")
    private String subject;

    /**
     * An array of new scopes. Optional. If a non-null value is given, the new scopes are set to all
     * existing access tokens. If an API call is made using `"Content-Type: application/x-www-form-urlencoded"`,
     * scope names listed in this request parameter should be delimited by spaces (after form encoding,
     * spaces are converted to `+`).
     */
    @SpeakeasyMetadata("form:name=scopes")
    private List<String> scopes;

    @JsonCreator
    public 1api1Percent7BserviceIdPercent7D1client1authorization1update1Percent7BclientIdPercent7DPostRequestBodyContentApplication1jsonSchema(
            @Nonnull String subject,
            @Nullable List<String> scopes) {
        this.subject = Optional.ofNullable(subject)
            .orElseThrow(() -> new IllegalArgumentException("subject cannot be null"));
        this.scopes = scopes;
    }
    
    public 1api1Percent7BserviceIdPercent7D1client1authorization1update1Percent7BclientIdPercent7DPostRequestBodyContentApplication1jsonSchema(
            @Nonnull String subject) {
        this(subject, null);
    }

    /**
     * The subject (= unique identifier) of the end-user who has granted authorization to the client
     * application.
     */
    public String subject() {
        return this.subject;
    }

    /**
     * An array of new scopes. Optional. If a non-null value is given, the new scopes are set to all
     * existing access tokens. If an API call is made using `"Content-Type: application/x-www-form-urlencoded"`,
     * scope names listed in this request parameter should be delimited by spaces (after form encoding,
     * spaces are converted to `+`).
     */
    public Optional<List<String>> scopes() {
        return Optional.ofNullable(this.scopes);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The subject (= unique identifier) of the end-user who has granted authorization to the client
     * application.
     */
    public 1api1Percent7BserviceIdPercent7D1client1authorization1update1Percent7BclientIdPercent7DPostRequestBodyContentApplication1jsonSchema withSubject(@Nonnull String subject) {
        this.subject = Utils.checkNotNull(subject, "subject");
        return this;
    }


    /**
     * An array of new scopes. Optional. If a non-null value is given, the new scopes are set to all
     * existing access tokens. If an API call is made using `"Content-Type: application/x-www-form-urlencoded"`,
     * scope names listed in this request parameter should be delimited by spaces (after form encoding,
     * spaces are converted to `+`).
     */
    public 1api1Percent7BserviceIdPercent7D1client1authorization1update1Percent7BclientIdPercent7DPostRequestBodyContentApplication1jsonSchema withScopes(@Nullable List<String> scopes) {
        this.scopes = scopes;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        1api1Percent7BserviceIdPercent7D1client1authorization1update1Percent7BclientIdPercent7DPostRequestBodyContentApplication1jsonSchema other = (1api1Percent7BserviceIdPercent7D1client1authorization1update1Percent7BclientIdPercent7DPostRequestBodyContentApplication1jsonSchema) o;
        return 
            Utils.enhancedDeepEquals(this.subject, other.subject) &&
            Utils.enhancedDeepEquals(this.scopes, other.scopes);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            subject, scopes);
    }
    
    @Override
    public String toString() {
        return Utils.toString(1api1Percent7BserviceIdPercent7D1client1authorization1update1Percent7BclientIdPercent7DPostRequestBodyContentApplication1jsonSchema.class,
                "subject", subject,
                "scopes", scopes);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String subject;

        private List<String> scopes;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The subject (= unique identifier) of the end-user who has granted authorization to the client
         * application.
         */
        public Builder subject(@Nonnull String subject) {
            this.subject = Utils.checkNotNull(subject, "subject");
            return this;
        }

        /**
         * An array of new scopes. Optional. If a non-null value is given, the new scopes are set to all
         * existing access tokens. If an API call is made using `"Content-Type: application/x-www-form-urlencoded"`,
         * scope names listed in this request parameter should be delimited by spaces (after form encoding,
         * spaces are converted to `+`).
         */
        public Builder scopes(@Nullable List<String> scopes) {
            this.scopes = scopes;
            return this;
        }

        public 1api1Percent7BserviceIdPercent7D1client1authorization1update1Percent7BclientIdPercent7DPostRequestBodyContentApplication1jsonSchema build() {
            return new 1api1Percent7BserviceIdPercent7D1client1authorization1update1Percent7BclientIdPercent7DPostRequestBodyContentApplication1jsonSchema(
                subject, scopes);
        }

    }
}
