/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * 1api1Percent7BserviceIdPercent7D1auth1authorization1failPostRequestBodyContentApplication1jsonSchemaReason
 * 
 * <p>The reason of the failure of the authorization request.
 * For more details, see [NO_INTERACTION] in the description of `/auth/authorization` API.
 */
public enum 1api1Percent7BserviceIdPercent7D1auth1authorization1failPostRequestBodyContentApplication1jsonSchemaReason {
    UNKNOWN("UNKNOWN"),
    NOT_LOGGED_IN("NOT_LOGGED_IN"),
    MAX_AGE_NOT_SUPPORTED("MAX_AGE_NOT_SUPPORTED"),
    EXCEEDS_MAX_AGE("EXCEEDS_MAX_AGE"),
    DIFFERENT_SUBJECT("DIFFERENT_SUBJECT"),
    ACR_NOT_SATISFIED("ACR_NOT_SATISFIED"),
    DENIED("DENIED"),
    SERVER_ERROR("SERVER_ERROR"),
    NOT_AUTHENTICATED("NOT_AUTHENTICATED"),
    ACCOUNT_SELECTION_REQUIRED("ACCOUNT_SELECTION_REQUIRED"),
    CONSENT_REQUIRED("CONSENT_REQUIRED"),
    INTERACTION_REQUIRED("INTERACTION_REQUIRED"),
    INVALID_TARGET("INVALID_TARGET");

    @JsonValue
    private final String value;

    1api1Percent7BserviceIdPercent7D1auth1authorization1failPostRequestBodyContentApplication1jsonSchemaReason(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<1api1Percent7BserviceIdPercent7D1auth1authorization1failPostRequestBodyContentApplication1jsonSchemaReason> fromValue(String value) {
        for (1api1Percent7BserviceIdPercent7D1auth1authorization1failPostRequestBodyContentApplication1jsonSchemaReason o: 1api1Percent7BserviceIdPercent7D1auth1authorization1failPostRequestBodyContentApplication1jsonSchemaReason.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

