/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nonnull;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class 1api1Percent7BserviceIdPercent7D1client1registration1updatePostRequestBodyContentApplication1jsonSchema {
    /**
     * Client ID.
     */
    @SpeakeasyMetadata("form:name=clientId")
    private String clientId;

    /**
     * Client registration access token.
     */
    @SpeakeasyMetadata("form:name=token")
    private String token;

    /**
     * Client metadata in JSON format that complies with [RFC 7591](https://datatracker.ietf.org/doc/html/rfc7591)
     * (OAuth 2.0 Dynamic Client Registration Protocol).
     */
    @SpeakeasyMetadata("form:name=json")
    private String json;

    @JsonCreator
    public 1api1Percent7BserviceIdPercent7D1client1registration1updatePostRequestBodyContentApplication1jsonSchema(
            @Nonnull String clientId,
            @Nonnull String token,
            @Nonnull String json) {
        this.clientId = Optional.ofNullable(clientId)
            .orElseThrow(() -> new IllegalArgumentException("clientId cannot be null"));
        this.token = Optional.ofNullable(token)
            .orElseThrow(() -> new IllegalArgumentException("token cannot be null"));
        this.json = Optional.ofNullable(json)
            .orElseThrow(() -> new IllegalArgumentException("json cannot be null"));
    }

    /**
     * Client ID.
     */
    public String clientId() {
        return this.clientId;
    }

    /**
     * Client registration access token.
     */
    public String token() {
        return this.token;
    }

    /**
     * Client metadata in JSON format that complies with [RFC 7591](https://datatracker.ietf.org/doc/html/rfc7591)
     * (OAuth 2.0 Dynamic Client Registration Protocol).
     */
    public String json() {
        return this.json;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Client ID.
     */
    public 1api1Percent7BserviceIdPercent7D1client1registration1updatePostRequestBodyContentApplication1jsonSchema withClientId(@Nonnull String clientId) {
        this.clientId = Utils.checkNotNull(clientId, "clientId");
        return this;
    }


    /**
     * Client registration access token.
     */
    public 1api1Percent7BserviceIdPercent7D1client1registration1updatePostRequestBodyContentApplication1jsonSchema withToken(@Nonnull String token) {
        this.token = Utils.checkNotNull(token, "token");
        return this;
    }


    /**
     * Client metadata in JSON format that complies with [RFC 7591](https://datatracker.ietf.org/doc/html/rfc7591)
     * (OAuth 2.0 Dynamic Client Registration Protocol).
     */
    public 1api1Percent7BserviceIdPercent7D1client1registration1updatePostRequestBodyContentApplication1jsonSchema withJson(@Nonnull String json) {
        this.json = Utils.checkNotNull(json, "json");
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        1api1Percent7BserviceIdPercent7D1client1registration1updatePostRequestBodyContentApplication1jsonSchema other = (1api1Percent7BserviceIdPercent7D1client1registration1updatePostRequestBodyContentApplication1jsonSchema) o;
        return 
            Utils.enhancedDeepEquals(this.clientId, other.clientId) &&
            Utils.enhancedDeepEquals(this.token, other.token) &&
            Utils.enhancedDeepEquals(this.json, other.json);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            clientId, token, json);
    }
    
    @Override
    public String toString() {
        return Utils.toString(1api1Percent7BserviceIdPercent7D1client1registration1updatePostRequestBodyContentApplication1jsonSchema.class,
                "clientId", clientId,
                "token", token,
                "json", json);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String clientId;

        private String token;

        private String json;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * Client ID.
         */
        public Builder clientId(@Nonnull String clientId) {
            this.clientId = Utils.checkNotNull(clientId, "clientId");
            return this;
        }

        /**
         * Client registration access token.
         */
        public Builder token(@Nonnull String token) {
            this.token = Utils.checkNotNull(token, "token");
            return this;
        }

        /**
         * Client metadata in JSON format that complies with [RFC 7591](https://datatracker.ietf.org/doc/html/rfc7591)
         * (OAuth 2.0 Dynamic Client Registration Protocol).
         */
        public Builder json(@Nonnull String json) {
            this.json = Utils.checkNotNull(json, "json");
            return this;
        }

        public 1api1Percent7BserviceIdPercent7D1client1registration1updatePostRequestBodyContentApplication1jsonSchema build() {
            return new 1api1Percent7BserviceIdPercent7D1client1registration1updatePostRequestBodyContentApplication1jsonSchema(
                clientId, token, json);
        }

    }
}
