/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class 1api1Percent7BserviceIdPercent7D1vci1offer1infoPostRequestBodyContentApplication1jsonSchema {
    /**
     * The identifier of the credential offer.
     */
    @SpeakeasyMetadata("form:name=identifier")
    private String identifier;

    @JsonCreator
    public 1api1Percent7BserviceIdPercent7D1vci1offer1infoPostRequestBodyContentApplication1jsonSchema(
            @Nullable String identifier) {
        this.identifier = identifier;
    }
    
    public 1api1Percent7BserviceIdPercent7D1vci1offer1infoPostRequestBodyContentApplication1jsonSchema() {
        this(null);
    }

    /**
     * The identifier of the credential offer.
     */
    public Optional<String> identifier() {
        return Optional.ofNullable(this.identifier);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The identifier of the credential offer.
     */
    public 1api1Percent7BserviceIdPercent7D1vci1offer1infoPostRequestBodyContentApplication1jsonSchema withIdentifier(@Nullable String identifier) {
        this.identifier = identifier;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        1api1Percent7BserviceIdPercent7D1vci1offer1infoPostRequestBodyContentApplication1jsonSchema other = (1api1Percent7BserviceIdPercent7D1vci1offer1infoPostRequestBodyContentApplication1jsonSchema) o;
        return 
            Utils.enhancedDeepEquals(this.identifier, other.identifier);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            identifier);
    }
    
    @Override
    public String toString() {
        return Utils.toString(1api1Percent7BserviceIdPercent7D1vci1offer1infoPostRequestBodyContentApplication1jsonSchema.class,
                "identifier", identifier);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String identifier;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The identifier of the credential offer.
         */
        public Builder identifier(@Nullable String identifier) {
            this.identifier = identifier;
            return this;
        }

        public 1api1Percent7BserviceIdPercent7D1vci1offer1infoPostRequestBodyContentApplication1jsonSchema build() {
            return new 1api1Percent7BserviceIdPercent7D1vci1offer1infoPostRequestBodyContentApplication1jsonSchema(
                identifier);
        }

    }
}
