/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import jakarta.annotation.Nullable;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;


public class 1api1Percent7BserviceIdPercent7D1vci1single1parsePostRequestBodyContentApplication1jsonSchema {
    /**
     * The access token that came along with the credential request.
     */
    @SpeakeasyMetadata("form:name=accessToken")
    private String accessToken;

    /**
     * The message body of the credential request.
     */
    @SpeakeasyMetadata("form:name=requestContent")
    private String requestContent;

    @JsonCreator
    public 1api1Percent7BserviceIdPercent7D1vci1single1parsePostRequestBodyContentApplication1jsonSchema(
            @Nullable String accessToken,
            @Nullable String requestContent) {
        this.accessToken = accessToken;
        this.requestContent = requestContent;
    }
    
    public 1api1Percent7BserviceIdPercent7D1vci1single1parsePostRequestBodyContentApplication1jsonSchema() {
        this(null, null);
    }

    /**
     * The access token that came along with the credential request.
     */
    public Optional<String> accessToken() {
        return Optional.ofNullable(this.accessToken);
    }

    /**
     * The message body of the credential request.
     */
    public Optional<String> requestContent() {
        return Optional.ofNullable(this.requestContent);
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The access token that came along with the credential request.
     */
    public 1api1Percent7BserviceIdPercent7D1vci1single1parsePostRequestBodyContentApplication1jsonSchema withAccessToken(@Nullable String accessToken) {
        this.accessToken = accessToken;
        return this;
    }


    /**
     * The message body of the credential request.
     */
    public 1api1Percent7BserviceIdPercent7D1vci1single1parsePostRequestBodyContentApplication1jsonSchema withRequestContent(@Nullable String requestContent) {
        this.requestContent = requestContent;
        return this;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        1api1Percent7BserviceIdPercent7D1vci1single1parsePostRequestBodyContentApplication1jsonSchema other = (1api1Percent7BserviceIdPercent7D1vci1single1parsePostRequestBodyContentApplication1jsonSchema) o;
        return 
            Utils.enhancedDeepEquals(this.accessToken, other.accessToken) &&
            Utils.enhancedDeepEquals(this.requestContent, other.requestContent);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            accessToken, requestContent);
    }
    
    @Override
    public String toString() {
        return Utils.toString(1api1Percent7BserviceIdPercent7D1vci1single1parsePostRequestBodyContentApplication1jsonSchema.class,
                "accessToken", accessToken,
                "requestContent", requestContent);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String accessToken;

        private String requestContent;

        private Builder() {
          // force use of static builder() method
        }

        /**
         * The access token that came along with the credential request.
         */
        public Builder accessToken(@Nullable String accessToken) {
            this.accessToken = accessToken;
            return this;
        }

        /**
         * The message body of the credential request.
         */
        public Builder requestContent(@Nullable String requestContent) {
            this.requestContent = requestContent;
            return this;
        }

        public 1api1Percent7BserviceIdPercent7D1vci1single1parsePostRequestBodyContentApplication1jsonSchema build() {
            return new 1api1Percent7BserviceIdPercent7D1vci1single1parsePostRequestBodyContentApplication1jsonSchema(
                accessToken, requestContent);
        }

    }
}
