/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package org.openapis.openapi.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * SupportedAttachment
 * 
 * <p>Supported attachment types. This property corresponds to the `attachments_supported`
 *  server metadata which was added by the third implementer's draft of OpenID Connect
 *  for Identity Assurance 1.0.
 */
public enum SupportedAttachment {
    EMBEDDED("EMBEDDED"),
    EXTERNAL("EXTERNAL");

    @JsonValue
    private final String value;

    SupportedAttachment(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<SupportedAttachment> fromValue(String value) {
        for (SupportedAttachment o: SupportedAttachment.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

